### ISSUE TITLE
Option 'Search' doesn't show results.

### ISSUE THREAD

**Issue by constructor-igor** [allegroai/trains#101]
Seems, search doesn't work:

https://demoapp.trains.allegro.ai/projects

![image](https://user-images.githubusercontent.com/1849690/73764750-32156080-477c-11ea-8d35-e94cc6b81a8b.png)

**Comment by bmartinn** [comment]
Hi @constructor-igor,

The search input field requires at least 3 characters before a search is performed - try adding a space after the search query shown in your screen capture.
