### ISSUE TITLE
Slow `scalar histogam loading`?

### ISSUE THREAD

**Issue by oak-tree** [allegroai/trains#104]
Hey 
we have trains installed on our cluster. we are using it for a few weeks already. We still facing some issues:
For example
![image](https://user-images.githubusercontent.com/667153/74315536-51b21780-4d80-11ea-93bc-a2091d2e6e5f.png)

Filtering `trains-api` server for **very long** `api calls` i.e more than a second

![image](https://user-images.githubusercontent.com/667153/74316450-3ba55680-4d82-11ea-8021-2a119afd6b43.png)

## Extra Information
**version**: trains ( v0.13 )
**settings**: we increased the memory for the trains `pods` 
any ideas?

**Comment by bmartinn** [comment]
Hi @oak-tree,

There can be many reasons for this slowness, chief among them is the amount of events/log lines reported to the server.

Increasing the memory is a good idea, but in order for that to affect Elasticsearch performance, you'll need to change the `ES_JAVA_OPTS` configuration (which is currently `-Xms2g -Xmx2g` meaning 2GB allocated to ES).
You can find this setting in the `docker-compose.yml` file under `services/elasticsearch/environment` (see [here](https://github.com/allegroai/trains-server/blob/135885b609408a274e11e74f694233c37d8d0449/docker-compose.yml#L35)). I suggest increasing to `-Xms4g -Xmx4g` and checking if this affects performance.

Please note you'll need twice as much memory available (so if you change this setting to 4GB, you'll need at least 8GB available on your machine - this is an Elsaticsearch/Java constraint).

If that does not solve the issue, please let me know so I can help you investigate it further :)

**Comment by oak-tree** [comment]
hey @bmartinn 
thanks, 
I will check the java memory configuration. Meanwhile, any other idea besides that?

**Comment by bmartinn** [comment]
Hi @oak-tree, 

Well, you can check the ES node's health and indices status to see if there's any obvious resource and/or performance issue (or simply to see if the indicates you have are quite large, which might indicate you need more memory...).

To do that, enter the following commands:
`$ curl http://localhost:9200/_cluster/health`
`$ curl http://localhost:9200/_cat/indices`

When you do, please share the command's outputs :)

**Comment by bmartinn** [comment]
@oak-tree I'm closing this issue, if the problem consists, feel free to reopen.
