### ISSUE TITLE
One specific user can't watch trains experiments 

### ISSUE THREAD

**Issue by Cptmaxon** [allegroai/trains#106]
for one user in our system we get for every experiment she attempts to open 
client side pop up : 
Error 14: Fields not defined for object: fields=(last_metrics_0bbb33608374ddba42f5782c7898cba7_32449770720f9959173a2f05b821a87a_value, last_metrics_0bbb33608374ddba42f5782c7898cba7_40d27a3a37f4b39e15f13b31efce253c_value, last_metrics_0bbb33608374ddba42f5782c7898cba7_f27f62eaa539b8889b53293b5fa1046b_value), object=Task

every other user works fine.

**Comment by shayh** [comment]
a fix is already on the way in the next version.
for now, you can paste this path to your server url in the browser nav bar and hit enter.
`/projects/*/experiments?columns=type&columns=name&columns=status&columns=project.name&columns=user.name&columns=started&columns=last_update&columns=last_iteration&order=last_update&filter=status:created`
it should reset the application column settings

**Comment by shyallegro** [comment]
a fix is already on the way in the next version.
for now, you can paste this path after your server url, in the browser nav bar, and hit enter.
`/projects/*/experiments?columns=type&columns=name&columns=status&columns=project.name&columns=user.name&columns=started&columns=last_update&columns=last_iteration&order=last_update&filter=status:created`
it should reset the application column settings

**Comment by Cptmaxon** [comment]
thanks the workaround worked.
