### ISSUE TITLE
🚀 Feature Request: PyTorch Lightning support

### ISSUE THREAD

**Issue by S-aiueo32** [allegroai/trains#107]
The other projects similar to TRAINS, like comet.ml and neptune.ai, integrate their features to PyTorch Lightning. Does TRAINS have any plans to do so?

**Comment by bmartinn** [comment]
Thanks @S-aiueo32 , that seems like a good idea! We will definitely do that :)
I'll update here once the PR is ready

**Comment by bmartinn** [comment]
PR is already waiting [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/929)
:)

**Comment by S-aiueo32** [comment]
@bmartinn Wow, thank you for the super fast work! It looks so great!

**Comment by S-aiueo32** [comment]
Because of the merge to master, I'll close here. Thanks!
