### ISSUE TITLE
Using trains/vcs-cache and venvs-builds

### ISSUE THREAD

**Issue by tomeramit** [allegroai/trains#108]
Hi,
I'm using trains, and I committed commit and launched experiment on it and things behave different from my local pc.
when I investigate it seems that my experiment is running from /.trains/vcs-cache/ which is on different branch although that /.trains/venvs-builds/3.5/task_repository seems on the correct branch.
Dont know why this is happening, I'm adding logs and stuff, let me know if something is missing in my report, thanks!

sdk.storage.cache.default_base_dir = ~/.trains/cache
sdk.storage.cache.size.min_free_bytes = 10GB
sdk.storage.direct_access.0.url = file://*
sdk.metrics.file_history_size = 100
sdk.metrics.matplotlib_untitled_history_size = 100
sdk.metrics.images.format = JPEG
sdk.metrics.images.quality = 87
sdk.metrics.images.subsampling = 0
sdk.network.metrics.file_upload_threads = 4
sdk.network.metrics.file_upload_starvation_warning_sec = 120
sdk.network.iteration.max_retries_on_server_error = 5
sdk.network.iteration.retry_backoff_factor_sec = 10
sdk.aws.s3.key = 
sdk.aws.s3.region = 
sdk.aws.boto3.pool_connections = 512
sdk.aws.boto3.max_multipart_concurrency = 16
sdk.log.null_log_propagate = false
sdk.log.task_log_buffer_capacity = 66
sdk.log.disable_urllib3_info = true
sdk.development.task_reuse_time_window_in_hours = 72.0
sdk.development.vcs_repo_detect_async = true
sdk.development.store_uncommitted_code_diff_on_train = true
sdk.development.support_stopping = true
sdk.development.worker.report_period_sec = 2
sdk.development.worker.ping_period_sec = 30
sdk.development.worker.log_stdout = true
agent.worker_id = trains-agent-lv-beast-keras-dl:gpu0
agent.worker_name = trains-agent-lv-beast-keras-dl
agent.python_binary = /home/lv-beast/miniconda3/envs/keras-dl/bin/python
agent.package_manager.type = pip
agent.package_manager.pip_version = <20
agent.package_manager.system_site_packages = true
agent.package_manager.force_upgrade = false
agent.package_manager.conda_channels.0 = defaults
agent.package_manager.conda_channels.1 = conda-forge
agent.package_manager.conda_channels.2 = pytorch
agent.venvs_dir = /home/lv-beast/.trains/venvs-builds
agent.vcs_cache.enabled = true
agent.vcs_cache.path = /home/lv-beast/.trains/vcs-cache
agent.venv_update.enabled = false
agent.pip_download_cache.enabled = true
agent.pip_download_cache.path = /home/lv-beast/.trains/pip-download-cache
agent.translate_ssh = true
agent.reload_config = false
agent.docker_pip_cache = /home/lv-beast/.trains/pip-cache
agent.docker_apt_cache = /home/lv-beast/.trains/apt-cache
agent.docker_force_pull = false
agent.default_docker.image = nvidia/cuda
agent.git_user = tomer.amit
agent.default_python = 3.7
agent.cuda_version = 102
agent.cudnn_version = 0
api.version = 1.5
api.verify_certificate = true
api.default_version = 1.5
api.http.max_req_size = 15728640
api.http.retries.total = 240
api.http.retries.connect = 240
api.http.retries.read = 240
api.http.retries.redirect = 240
api.http.retries.status = 240
api.http.retries.backoff_factor = 1.0
api.http.retries.backoff_max = 120.0
api.http.wait_on_maintenance_forever = true
api.http.pool_maxsize = 512
api.http.pool_connections = 512
api.api_server = http://localhost:8008
api.web_server = http://localhost:8080
api.files_server = http://localhost:8081
api.host = http://localhost:8008

Executing task id [69b4f89f0c5f479a929c3a1faa824e1e]:
branch = feature/1_sample_to_ct
version_num = 56e568af81f2e018e7bc1f0b38bf25ee30f9d053
tag = 
entry_point = unpaired_real_to_ct.py
working_dir = LvObjects/Lv3D/DeepTomography/Scripts

Using base prefix '/home/lv-beast/miniconda3/envs/keras-dl'
New python executable in /home/lv-beast/.trains/venvs-builds/3.5/bin/python
Installing setuptools, pip, wheel...
done.

Using cached repository in "/home/lv-beast/.trains/vcs-cache/MachineLearning.6b0aaffa69d428f2574a1d5068d3ee6b/MachineLearning"

2020-02-24T16:31:32.450Z trains-agent-lv-beast-keras-dl:gpu0 DEBUG Note: checking out '56e568af81f2e018e7bc1f0b38bf25ee30f9d053'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 56e568a remove build data
type: git
url: https://bodyvisionmedical.visualstudio.com/DefaultCollection/LungVision/_git/MachineLearning
branch: HEAD
commit: 56e568af81f2e018e7bc1f0b38bf25ee30f9d053
root: /home/lv-beast/.trains/venvs-builds/3.5/task_repository/MachineLearning
Applying uncommitted changes

**Comment by bmartinn** [comment]
Hi @tomeramit , I'm not sure what you mean by "it behaves differently than on the local pc"?

Regrading the commit/branch you are seeing:
- `~ /.trains/vcs-cache/` holds a cache copy of the entire git repository. Caching the git repository really accelerates the spin time of the experiments, as we only need to pull the changes every time a new experiment is executed (instead of cloning the entire repo).
- `~/.trains/venvs-builds/3.5/task_repository/` stores a copy of the git repository, checked to the specific commit id, with all the git uncommitted changes applied to it. This is where the code will be executed from. This folder will be deleted on the next execution, and will be recreated for the next experiment.

What do you feel is misbehaving in the `trains-agent` execution context?
Are you running it in docker-mode or in virtual-environment mode?

**Comment by tomeramit** [comment]
I'm running in a virtual environment mode.
I did new commit and launched an experiment from on this commit when for example I changed a flag from true to false.

although this is the correct commit id (56e568af81f2e018e7bc1f0b38bf25ee30f9d053) my execution behaves like it on different branch (without the change of the flag)

I investigated more and it seems that somehow my script is calling things out of the trains folder (maybe some issues with paths or something), probably it's a bug in my code, but if this relates to something that sounds familiar let me know

thanks!

**Comment by bmartinn** [comment]
Hi @tomeramit ,
 > I investigated more and it seems that somehow my script is calling things out of the trains folder (maybe some issues with paths or something), probably it's a bug in my code, but if this relates to something that sounds familiar let me know

I think you are right, and that's the issue. I'll expand on how the *trains-agent* works, I think it will make things more clear.

The *trains-agent* will set the entire environment inside the virtual-environment. This means the python packages and the repository containing the code itself.

If your code relies on external modules, you have one of two options:
- Package the external python module in a wheel, then add that wheel to the Experiment's "Installed Packages" section (You do not have to use an artifactory for the wheel, you can just put a full link to a shared folder containing the wheel file)
- Add the external modules as Git submodules. Basically a git submodule is a form of soft link to a directory that points to another repository, at a specific commit. You can read more about it [here](https://github.blog/2016-02-01-working-with-submodules/) and [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

With both options, you will be able to launch your experiment on any machine, regardless of where the original code/experiment was located.

What do you think?

**Comment by tomeramit** [comment]
I have a submodule inside my repo, and in order for it to work, I need to set the python paths to inner folders inside my submodule
as I see it I have 2 options,

First one is to be able to add the python paths based on the folder of the agent (I know that every agent create a different folder, I can do some stuff hardcoded, but it seems a bit hacky)

The second one is to change the import on the submodule to relative (but it's long, and I saw some disadvantages to that)

do you have another idea? (or maybe I miss understood the way you meant when you mentioned to use submodules)

**Comment by bmartinn** [comment]
@tomeramit , if you already have submodules in your main git repository,
then you could add the following code snippet in the main python code. 
This code will add the submodules to your python path and will hold both while developing on your machine and during the *trains-agent* remote execution:
``` python
import sys
import os
sys.path.insert(0, os.path.abspath('../submodules_folder/mymodule'))
```
Notice that this will add the submodule path based on the current working dir, which is exactly what we want, to avoid adding absolute paths that will break the moment we move the code to another machine (this is not directly related to *trains-agent*, but is good practice when writing robust code :)

Usually the current working directory is the main root folder of your repository, but you can always verify in runtime with:
```python
import os
print(os.getcwd())
```

**Comment by tomeramit** [comment]
thanks! I think it may work
