### ISSUE TITLE
Override config location

### ISSUE THREAD

**Issue by adiell** [allegroai/trains#11]
Hi,
Is there a way to specify the location of the configuration file, instead of it's default (`~/trains.conf`)?
The use case is running on AWS Sagemaker (or similar).
Thanks.

**Comment by bmartinn** [comment]
Yes!
Use the TRAINS_CONFIG_FILE environment variable to set an override full path to your trains config file.

**Comment by bmartinn** [comment]
Closed, moved to FAQ
