### ISSUE TITLE
Please reset the demo server at midnight

### ISSUE THREAD

**Issue by qiuwei** [allegroai/trains#114]
Although it is claimed that the trains demo server is reset at midnight,  it does not seem to do so.
One could find lots of experiments from months ago.

It is misleading and might cause a leak of information.

Thanks!

**Comment by bmartinn** [comment]
Hi @qiuwei I think you are correct.
We will change the policy to once a week, and make sure it actually resets.

We have a feeling  the demo server is quite convinient for people to use, so we figured it will be nice to at least store the data for a while, if we can. That said a week sounds long enough. What do you think?

**Comment by qiuwei** [comment]
@bmartinn thanks for the reply. I think a week is quite OK.

One thing still bugs me is that the default is actually quite dangerous in some use cases, especially when trains is used in production.

It could easily happen that someone forgets to initialize the trains client, then without any warning, the very detailed log is pushed to the demo website.

I do consider the current default makes the adoption of trains a breeze. However, I think it might be nice to let the users specify the sever url explicitly in the code as an alternative to the config in the home directory.

**Comment by bmartinn** [comment]
Yes, this balance is exactly what we had in mind. On the one hand easy to on-board, on the other is easy to setup for your own backend server.

Specifically, @qiuwei if you like to set the host server in code, you can use [Task.set_credentials](https://allegro.ai/docs/task.html#trains.task.Task.set_credentials), before initializing the experiment:
```python
from trains import Task
Task.set_credentials(api_host='http://localhost:8008', web_host='http://localhost:8080', files_host='http://localhost:8081',  key='optional_credentials',  secret='optional_credentials')
task = Task.init('examples', 'just a test')
```

Notice that if you want, you can also provide the credentials using the same `Task.set_credentials` call, quite useful when working on a remote notebook for example.

Regrading the security issue you raised.
I would recommend setting a DNS entry (either on the company firewall, or even in /etc/hosts) to point `demoapi.trains.allegro.ai` to `127.0.0.1`, thus blocking the api server.

**Comment by qiuwei** [comment]
Thanks for the detailed instructions. 
It really helps!
