### ISSUE TITLE
Plot multiple vector data as a 2D scatter diagram

### ISSUE THREAD

**Issue by livneros** [allegroai/trains#115]
Hey,
Can I send multiple series to the report_scatter2d method?
I would like to draw a graph like this one:
![image](https://user-images.githubusercontent.com/42512692/76700125-f21b9480-66bc-11ea-9605-6be33acd78fc.png)

**Comment by JDennisJ** [comment]
Hi @livneros,

Currently, you can have multiple scatter2d series by sending the scatter with the same title and iteration:

```
scatter2d_1 = np.hstack((np.atleast_2d(np.arange(0, 10)).T, np.random.randint(10, size=(10, 1))))
logger.report_scatter2d("example_scatter", "series_1", iteration=1, scatter=scatter2d_1,
                        xaxis="title x", yaxis="title y")

scatter2d_2 = np.hstack((np.atleast_2d(np.arange(0, 10)).T, np.random.randint(10, size=(10, 1))))
logger.report_scatter2d("example_scatter", "series_2", iteration=1, scatter=scatter2d_2,
                        xaxis="title x", yaxis="title y")
```
 This example with create the follow:

![image](https://user-images.githubusercontent.com/54317609/76700572-80921500-66c1-11ea-80aa-48a49c09e430.png)

Can this do the trick for you?

**Comment by livneros** [comment]
perfect!, Thank you very much.
