### ISSUE TITLE
Offline experiments option

### ISSUE THREAD

**Issue by Alexfinkelshtein** [allegroai/trains#117]
Hi guys,
I came across a use-case that is not supported but can be very useful for me, running offline experiments, and later reading the experiment info on a server.
I'll be happy if you support it.

**Comment by bmartinn** [comment]
Hi @Alexfinkelshtein , thank you for the feature request, it sounds great.

I think that a global setting makes sense here, what do you think?

Just throwing an idea here, maybe something like:
```python
Task.set_offline_mode(local_log_file='~/my_log_file.json')
task = Task.init('examples', 'an offline example')
```

Then sometime later when we have internet connection:
```bash
$ trains sync --log=~/my_log_file.json
```

**Comment by lamhoangtung** [comment]
@bmartinn Agree

**Comment by amarczew** [comment]
maybe would be better a dir instead of `.json` file. Because you also need to save artifacts and plots

**Comment by bmartinn** [comment]
Good news guys, offline mode is now available 🎊 
With the new release of [trains 0.16](https://github.com/allegroai/trains/releases/tag/0.16.0) you can set [Task.set_offline](https://github.com/allegroai/trains/blob/ffdf2e5c4c547a39120f7abaf5814cec723f7a33/trains/backend_interface/task/task.py#L1795) to True. 
Later you can import your session (either the zip file or folder) with [Task.import_offline_session](https://github.com/allegroai/trains/blob/ffdf2e5c4c547a39120f7abaf5814cec723f7a33/trains/task.py#L1690).

The offline session includes all console output, metric logs & artifacts.
(It does not include stored models, let us know if you would like to see that included as well :)

**Comment by amarczew** [comment]
@bmartinn great news!! I am looking forward to update my projects to use it!!

Thank you so much!! :smiley:
