### ISSUE TITLE
Audio support 

### ISSUE THREAD

**Issue by adiyoss** [allegroai/trains#120]
Hi,
Is there any way to plot/listen to audio files using the web UI? Not an image, actually listen to the files.  

Thanks!
And btw, thanks for this great tool :)

**Comment by bmartinn** [comment]
Hi @adiyoss ,
A few questions on the audio feature:
- What is the audio format?
- Are you already logging the audio as debug media with Tensorboard/X ?

Regardless there is currently a hack that will allow you to log audio, unfortunately due to a web UI bug there is no nice media playback button (still usable though).
We will have a dedicated `report_media` in the next trains version, but until then you can use `report_image` with a local audio file (basically anything the browser supports)

```python
from trains import Task
task = Task.init(project_name="examples", task_name="audio reporting")
task.get_logger().report_image("audio", "wav test", iteration=1, local_path='./ff-16b-2c-44100hz.wav')
```

After executing the code you can press on the "Open Image" link and the audio file will be opined in a new tab with proper media control (notice that *wav* is only supported on Chrome, but most other audio formats are supported on both)
![Screenshot-2020-04-05](https://user-images.githubusercontent.com/51887611/78506003-b2a60c80-777f-11ea-8673-ce763888aada.png)

What do you think?

**Comment by adiyoss** [comment]
Thanks for the quick replay!
Unfortunately, it doesn't really work. Browsers (chrome and safari) do not always present the "unable to open" image. 
What I tried to do is to parse the wav from the raw HTML, however this is not a stable solution, more of a hack. 

Regarding your questions:
1) Mainly .wav format
2) At the moment I'm logging the wav files using TensorboardX. However, I do not have any hard feelings for it, if you will have support for audio using your logger I'll switch.

**Comment by adiyoss** [comment]
The version is  v0.13 and on your server it is v0.14. I'll try to update for the latest version, maybe that will fix that.
And yeah sure! lets add support for that too, that would be amazing :)

**Comment by adiyoss** [comment]
Ok I updated the version and now it is working! :)
Now, the problem is that it opens the link to the TRAINS server, and since I'm using a proxy I need to change the IP to localhost...can live with it, but still a stable solution would great.

**Comment by bmartinn** [comment]
@adiyoss that's awesome.
Out of curiosity, you mention proxy, I assume you can access the *trains-server*, but the trains file server (storing the actual audio sample) should be accessible as well through the same proxy, shouldn't it?

**Comment by bmartinn** [comment]
Hi @adiyoss, 

Please see the latest RC - we included audio support for TensorFlow and TensorBoardX:
`pip install trains==0.14.2rc0`

Usage example (using TensorFlow 2.0):
```python
import tensorflow as tf
import numpy as np
from trains import Task

task = Task.init(project_name='examples', task_name='Tensorflow v2 Audio')

file_writer = tf.summary.create_file_writer("/tmp/log")

# generate sin wave
sample_rate = 44100
freqs = 440
dummy_audio = np.arange(sample_rate * 2, dtype=np.float32)
dummy_audio = np.cos(dummy_audio * (2.0 * freqs * np.pi / sample_rate))

# Using the file writer, log the reshaped image
with file_writer.as_default():
    # single mono
    tf.summary.audio("my/audio_mono", tf.convert_to_tensor(np.reshape(dummy_audio, [1, dummy_audio.size, 1])),
                     sample_rate=sample_rate, step=0)
    # single stereo
    tf.summary.audio("my/audio_stereo", tf.convert_to_tensor(np.reshape(dummy_audio, [1, dummy_audio.size//2, 2])),
                     sample_rate=sample_rate, step=0)
    # batch of two audio streams
    tf.summary.audio("my/audio_batch", tf.convert_to_tensor(np.reshape(dummy_audio, [2, dummy_audio.size//2, 1])),
                     sample_rate=sample_rate, step=0)
```

**Comment by adiyoss** [comment]
Amazing! thanks!!
Will do and let you know how it is working :)

**Comment by adiyoss** [comment]
@bmartinn 
Regarding the proxy, the answer is yes. 
But this can be done using tunneling. If I understood the question...

**Comment by bmartinn** [comment]
Hi @adiyoss 
I just wanted to point out that the actual audio file (like any debug sample or artifact), is stored with a full URL on the experiment itself. That means that if I executed the experiment and accessed the `trains-server` on IP `1.2.3.4` the audio links and artifacts will be registered on `1.2.3.4:8081/...` that means that if you tunnel to the server, your browser will still try to reach the links on `1.2.3.4:8081/` regardless of the "new" trains-server IP. Now if you are using a VPN, then there should be no problem as you are virtually  on the same LAN, but if you do port tunneling over ssh, things might get a bit more complicated. 
I guess the takeaway is that it is always preferable to use a host-name over IP,  when configuring the `trains-server` :)

**Comment by bmartinn** [comment]
Hi @adiyoss,
[v0.15](https://github.com/allegroai/trains-server/releases/tag/0.15.0) is out :confetti_ball: with full audio support inside the web UI.
