### ISSUE TITLE
Async model checkpoint upload fails when the file is renamed

### ISSUE THREAD

**Issue by iakremnev** [allegroai/trains#123]
### Bug
While using `TrainsLogger` in Pytorch-Lightning, the latter saves model checkpoint via `_atomic_save` function, which renames the file right after calling `torch.save`. Consequently, train's hook on `torch.save` tries to asynchronously upload `.ckpt.part` file and fails.

The original issue on Pytorch-Lightning Github: https://github.com/PyTorchLightning/pytorch-lightning/issues/1466

**Comment by iakremnev** [comment]
https://allegroai-trains.slack.com/archives/CTK20V944/p1586771229061800
> I think the best solution is for Trains to create a copy of the file and upload it in the background. That said the name will still end with .part

**Comment by bmartinn** [comment]
Hi @iakremnev , 
Seems like any renaming or deleting a stored model file before the async upload is completed will cause this error. What we will do is create a temp copy of the model file, upload it and then delete the temp file when upload is completed.

**Comment by bmartinn** [comment]
Hi @iakremnev,

Please see if the latest RC fixes the problem:
`pip install trains==0.14.2rc0`

**Comment by iakremnev** [comment]
Yes, the issue is solved! Thanks for the quick fix ❤️

**Comment by S-aiueo32** [comment]
@bmartinn Is this really fixed? I'm facing the same issue. I use`trains==0.15.1` and `trains-server== 0.15.1-367`  through `TrainsLogger` of `pytorch-lightning-bolts==0.1.0` as follow:
```python
logger = TrainsLogger(auto_connect_frameworks=True)
```

**Comment by bmartinn** [comment]
@S-aiueo32 what exactly are you experiencing?
Yes the issue was fixed, but recently they moved the `TrainsLogger` to `pytorch-lightning-bolts` and I lost track.
