### ISSUE TITLE
Sorting a numeric hyperparameter column or metric column sorts lexicographically instead of numerically.

### ISSUE THREAD

**Issue by WillNichols726** [allegroai/trains#124]
See title. Numeric columns should be sorted numerically, not lexicographically.

![image](https://user-images.githubusercontent.com/45394583/79123377-05775980-7d68-11ea-8364-d2981198d728.png)

**Comment by bmartinn** [comment]
Hi @WillNichols726 ,

Following a short check with the backend guys, just wanted to update we will fix this issue in the next Trains Server release :)

**Comment by bmartinn** [comment]
Hi @WillNichols726 
I forgot to update, but the bug was fixed in *trains-server* 0.15, feel free to test on the demo server :)
