### ISSUE TITLE
Documentation `Logger.report_scatter2d` mix of " and '

### ISSUE THREAD

**Issue by czotti** [allegroai/trains#129]
I just came across a copy/paste issue from the documentation, there is a mix of `"` and `'`
https://github.com/allegroai/trains/blob/c3acfbac20323860ab16a205f2f5ffab2ed88460/trains/logger.py#L340

**Comment by bmartinn** [comment]
Hi @czotti , thank you for catching it !
A fix should be committed tomorrow, alongside a few other doc-string improvements :)

**Comment by jkhenning** [comment]
Hi @czotti 
Documentation fix (and more) was pushed today :)
Thanks again for taking the time to help us improve Trains!

**Comment by bmartinn** [comment]
Closing this issue, doc string was fixed.
Pleas re-open if the issue re-surfaces.
