### ISSUE TITLE
frozen worker

### ISSUE THREAD

**Issue by elinep** [allegroai/trains#135]
Hi,

From time to time my trains-agent workers freeze.

Currently, I have one task marked as "complete" (which seems plausible given the log) still enqueued in the worker. My only option to free the worker is to reset the task and lose the data.

I have another "running" task which is frozen with no outputs for a while. This task can be aborted to free the worker.

I use trains v14.2 and trains-server v14.

Is it a known issue? 

Thanks

**Comment by jkhenning** [comment]
Hi @elinep

Thanks for reporting this :)

A few questions to clarify:
- What version of Trains Agent are you using?
- Are you using the Trains Agent in `--docker` mode?
- What do you mean when you say your completed experiment is "still enqueued in the worker"? Does that mean you still see the worker listed in the workers page as running this experiment?
- Can you see if there's any text in the completed experiment's **INFO** panel, **STATUS MESSAGE** field?
- Can you see if the running experiment's **LAST UPDATED AT** field under the **INFO** panel is also frozen, or is it getting updated from time to time?

**Comment by elinep** [comment]
- **What version of Trains Agent are you using?**
0.13.3
- **Are you using the Trains Agent in --docker mode?**
the trains-agent is running inside our own docker image
- **What do you mean when you say your completed experiment is "still enqueued in the worker"?**
The experiment appears in http://trainserver/workers-and-queues/workers
- **Does that mean you still see the worker listed in the workers page as running this experiment?**
yes
- **Can you see if there's any text in the completed experiment's INFO panel, STATUS MESSAGE field?**
`STATUS MESSAGE:
Changed by trains-agent trains-agent-777949bb7c-4j4wq:gpuGPU-30e3a01d-5a6e-cf57-85ab-10d4e05f85e2`
- **Can you see if the running experiment's LAST UPDATED AT field under the INFO panel is also frozen, or is it getting updated from time to time?**
Both experiments (running and complete) are updated frequently ("Update Time: a few seconds ago")

Thank you for your time.

**Comment by bmartinn** [comment]
Hi @elinep 
From the looks of it, it seems that somehow the Task state was changed, and the thread that checks it died, otherwise it would have terminate the process. (BTW, could it be that the Task changed its own status? Just clarifying, this is supported, but it might help reproduce / locate the bug)
Anyhow could you change to the latest trains-agent, we have fixed a few issues relating stability.
`pip install trains-agent==0.14.2rc2`

Regrading the Task stuck in running, that might have to do with the actual python code running.
Any stdout/stderr prints from that process are immediately logged in the Task, so if you see nothing it does mean it is stuck, but the process is still running.
Which *trains* version are you using with this specific Task ? (I remember vaguely that we did see this behavior a few times, i.e. process stuck when leaving, but it was fixed with 0.14.2 (I think))

As for the Task in completed mode, I guess the only way to kill the process save the logs is, either connect to the container and kill the trains-agent or restart the container :(

**Comment by elinep** [comment]
The script doesn't touch the status.
We use `trains == 0.14.2` for both tasks

I ran `ps aux` on several machines:

A) Task still Running / worker busy:
```
root@trains-agent-777949bb7c-xw46z:/app# ps aux 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  2.1  0.1 263284 51896 ?        Ssl  May12 240:19 /usr/bin/python3 /usr/local/bin/trains-agent daemon --queue kube
root       265  5.6 10.9 16228604 3609288 ?    Sl   May13 533:20 /root/.trains/venvs-builds/3.6/bin/python -u train_script.py
root     24284  0.0  0.0  18508  3476 pts/0    Ss+  May18   0:00 /bin/bash
root     24307  1.0  0.0  18508  3268 pts/1    Ss   06:42   0:00 bash
root     24321  0.0  0.0  34404  2808 pts/1    R+   06:42   0:00 ps aux
```

B) Task Completed / worker busy:
```
root@trains-agent-777949bb7c-9dtgx:/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1 47.9  0.1 260808 49708 ?        Ssl  Apr30 13707:03 /usr/bin/python3 /usr/local/bin/trains-agent daemon --queue kube
root       363 1089458  0.5 2132380 278388 ?   R    Apr30 21142800:27 /root/.trains/venvs-builds/3.6/bin/python -u src/train_script.py
root       441  0.0  0.5 2240644 255304 ?      D    May07   0:09 /root/.trains/venvs-builds/3.6/bin/python -u train_script.py
root       562  0.0  0.5 2132392 278464 ?      D    May07   5:09 /root/.trains/venvs-builds/3.6/bin/python -u src/train_script.py
root       642  0.0  0.5 2240668 255308 ?      D    May12   3:53 /root/.trains/venvs-builds/3.6/bin/python -u train_script.py
root       729  0.0  0.5 2240660 255944 ?      D    May13   0:07 /root/.trains/venvs-builds/3.6/bin/python -u train_script.py
root       811  0.2  0.5 2240656 255872 ?      Dl   May14  24:08 /root/.trains/venvs-builds/3.6/bin/python -u train_script.py
root       898  0.3  0.0  18508  3344 pts/0    Ss   06:45   0:00 bash
root       912  0.0  0.0  34404  2908 pts/0    R+   06:45   0:00 ps aux
```

C) Task running, no issue:
```
root@trains-agent-777949bb7c-2fzxj:/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  2.7  0.2 312748 95720 ?        Ssl  Apr07 1709:09 /usr/bin/python3 /usr/local/bin/trains-agent daemon --queue kube
root      1316  0.0  0.0      0     0 ?        Z    Apr16   0:35 [python] <defunct>
root      1372  0.0  0.0      0     0 ?        Z    Apr16   0:06 [python3.6] <defunct>
root      1414  0.0  0.0      0     0 ?        Z    Apr16   0:05 [python3.6] <defunct>
root      1466  0.0  0.0      0     0 ?        Z    Apr16   0:13 [python] <defunct>
root      7929  0.0  0.0      0     0 ?        Z    Apr09   0:37 [python] <defunct>
root     13332  317 10.7 16165924 3518368 ?    Rl   06:42  14:49 /root/.trains/venvs-builds/3.6/bin/python -u train_vae.py
root     15738  0.0  0.0      0     0 ?        Z    Apr17   0:46 [python] <defunct>
root     15742  0.0  0.0      0     0 ?        Z    Apr17   0:46 [python] <defunct>
root     15746  0.0  0.0      0     0 ?        Z    Apr17   0:46 [python] <defunct>
root     23420  0.0  0.0  18508  3232 pts/0    Ss   06:47   0:00 bash
root     23542  0.0  0.0  34404  2744 pts/0    R+   06:47   0:00 ps aux
root     28494  0.0  0.0      0     0 ?        Z    Apr20   7:02 [python] <defunct>
root@trains-agent-777949bb7c-2fzxj:/app# 
```

There are several process still running on machine B.

We will update trains-agent and keep you updated if we see this issue again.

Thanks for your support.

**Comment by bmartinn** [comment]
Closing issue (re-open if the problem resurfaces)
