### ISSUE TITLE
Pass parameters to plotly through report methods for customization

### ISSUE THREAD

**Issue by pedropalb** [allegroai/trains#136]
Hi!
I suggest you add a kwargs parameter to report methods so one can pass parameters all the way down to plotly enhancing the customization options. For example, I would like to set the axes ranges when using report_line_plot like:

```python
logger.report_line_plot(title, series, iteration, xtitle, ytitle, xaxis_range=[0, 1])
```

Is it possible to do it in the current version of TRAINS?
Thanks!

**Comment by bmartinn** [comment]
Thanks for the suggestion @pedropalb !
Yes, can't see any reason we could not add it.
I was thinking maybe we should add generic plotly.js layout configuration.
something like: 
```python
logger.report_line_plot(title, series, iteration, xtitle, ytitle, extra_layout={'xaxis': {'showticklabels': False, 'range': [0, 5],  'tickfont': {'color': 'magenta'}}})
```

What do you think?

**Comment by WillNichols726** [comment]
This would be a great feature! I recently saw a presentation on Weights and Biases, and you can directly log a matplotlib or plotly object. https://docs.wandb.com/library/log#custom-plots It'd be great to have that feature in Trains!

**Comment by bmartinn** [comment]
Thanks @WillNichols726 ! 
Actually matplotlib you can already be directly logged (see automagic [example](https://github.com/allegroai/trains/blob/master/examples/matplotlib_example.py))  and the same idea is being worked on for plotly objects :)

That said, I think we should push forward with additional control for the reports as suggest above, can't actually see any reason not to ...

**Comment by WillNichols726** [comment]
@bmartinn Agreed, would love to see both options in Trains one day!

For the automagic example, would that work on headless systems?

**Comment by bmartinn** [comment]
Hi @WillNichols726 
>For the automagic example, would that work on headless systems?

If you are running your code manually (i.e. not with *trains-agent*) then you have to set the backend to Agg yourself, and the automagic will work.
If you are running with *trains-agent* , no need to worry, it will take care of it (i.e. setting the backend to Agg to allow headless execution).

**Comment by bmartinn** [comment]
@WillNichols726 good news, v0.15 is out :balloon:  with this feature [added](https://github.com/allegroai/trains/blob/master/trains/logger.py#L401)
Sending a full plotly object is on the agenda for the next version :)

**Comment by WillNichols726** [comment]
@bmartinn Awesome, thanks for following up!

**Comment by pedropalb** [comment]
Thanks for the new feature, @bmartinn!
Waiting for the next feature: send the full plotly object, because now, I'd like to set the stackgroup property of a go.Scatter so I can plot a probability distribution over a time series for each epoch.

**Comment by bmartinn** [comment]
@pedropalb good news, the latest RC already contains the full plotly report feature, see [example](https://github.com/allegroai/trains/blob/master/examples/reporting/plotly_reporting.py):
```bash
$ pip install trains==0.15.1rc0
```
