### ISSUE TITLE
Plan for view git diff in Web UI

### ISSUE THREAD

**Issue by VoVAllen** [allegroai/trains#14]
Is there any planned release date for git diff view in Web UI? Also is there any workaround I can do at current stage? (where is it stored?)

**Comment by bmartinn** [comment]
Assuming you have two commit versions:
```
e18964b5dff0fe9639ec487087e8aa413f9272a1
85f702d5941890496dd49daf3f9127c69c57dfb2

```
This link will compare the two commits:

`
https://github.com/allegroai/trains/compare/e18964b5dff0fe9639ec487087e8aa413f9272a1..85f702d5941890496dd49daf3f9127c69c57dfb2?diff=split
`

@VoVAllen I guess it won't be too complex to add a button in the UI opening this link for you  ;)
What do you think?

**Comment by VoVAllen** [comment]
Thanks! Trains is really helpful for finetuning models! Another question is how to see the uncommited git diff? I think it is also recorded right?

**Comment by bmartinn** [comment]
Thanks @VoVAllen we love compliments :)
Yes, next *TRAINS-server* version (coming soon) will display git diff, and a few more treats ...
