### ISSUE TITLE
task.execute_remotely should update task state

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains#141]
Currently, 

`task.execute_remotely("default", False, True)` will send the task to the queue without updating its state. The function will reset the task and enqueue it, then exit the current process. Therefore in the web UI, the task is shown as completed and stays in that state, even if the task was picked by an agent and is being executed remotely.

task.execute_remotely should do something like:

```
def execute_remotely(self, queue_name=None, clone=False, exit_process=True):
        ....
        # leave this process.
        if exit_process:
            LoggerRoot.get_base_logger().warning('Terminating local execution process')
            self.mark_stopped()  # <--- We explicitly mark the task as stopped
            exit(0)
```

Currently, to get the correct behavior, I have to do:

```
        if Task.running_locally():
            task.mark_stopped()  # Make sure task is mark as stopped so that its state is correctly switched to "pending" afterwards
            task.execute_remotely(queue_name="default")
        # Now running in agent
        ...
```

**Comment by bmartinn** [comment]
@H4dr1en I think I'm missing a few details.
But first, a bit of under-the-hood explaining.
The Task itself has a few [states](https://github.com/allegroai/trains/blob/master/trains/backend_interface/task/task.py#L84), and a state-machine in the backend. 
You cannot enqueue a Task unless it is in  "created" state (draft/editable in the UI).
Calling `task.reset()` will reset the task outputs and change it's state to "created"
`task.enqueue` will change the state to "queued" and the *trains-agent* will start running it and change the state to "in_progress".
It seems the only way the task will be completed would be if the *trains-agent* executed it...

You can see the actual flow here: [closing](https://github.com/allegroai/trains/blob/master/trains/task.py#L2436) [change state / clone](https://github.com/allegroai/trains/blob/master/trains/task.py#L2447) [enqueue](https://github.com/allegroai/trains/blob/master/trains/task.py#L2455)

**Comment by H4dr1en** [comment]
Thanks for the explanations! I cannot come up with an easy reproducible example at the moment, so I just close this issue and reopen it only if I can share such example.
