### ISSUE TITLE
Error when installing from source: six and pathlib2 required

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains#142]
Because `setup.py` imports `six` and `pathlib2`, the installation of trains will fail in a new environment, because these packages are not installed. They should be installed by the user before installing trains/trains-agent, which is not intuitive not straightfoward IMO.

Both these dependencies can be removed with a very little refactoring effort, WDYT?

**Comment by bmartinn** [comment]
@H4dr1en very true.
Do you feel like PR-ing a fix?
