### ISSUE TITLE
Disable automatic output model snapshot tracking

### ISSUE THREAD

**Issue by rorph** [allegroai/trains#146]
Hello,

Is there an option to disable the output model snapshot while still keep tracking of the training framework?

EG: I want to save the best scoring model as output model, however, because snapshot tracking is enabled there's a race condition, when a new snapshot comes in it overwrites the best model set.

Thanks 

Great project BTW

**Comment by bmartinn** [comment]
Thank you @rorph , kind words are always appreciated :)
I think I'm missing some information on what you are looking for, but it looks similar to one of the latest additions :)
See the PR for PyTorch ignite [here](https://github.com/pytorch/ignite/pull/1135) and the [discussion](https://github.com/pytorch/ignite/issues/1056)
Is this the use case ? 

With trains 0.15.1rc0 we added a few callbacks to allow you to interfere with the model registration,
You can see the use case [here](https://github.com/jkhenning/ignite/blob/fix_trains_checkpoint_n_saved/ignite/contrib/handlers/trains_logger.py#L734)

You can also disable the tracking [automagic](https://github.com/allegroai/trains/blob/master/trains/task.py#L267) with :
```python
from trains import Task
Task.init('examples', 'no tracking', auto_connect_frameworks={'pytorch': False})
```
And then manually log a model:
```python
from trains import OutputModel
OutputModel().update_weights('my_best_model.bin')
```

**Comment by rorph** [comment]
Hey @bmartinn , thanks for the reply.
I saw the disable automagic options at the documentation, however, I only wanted to disable the snapshop feature in specific, all the other metrics produced by the automagic still pertinent.

Looking at the PR , I think I probably can circumvent this issue by setting a event that never saves it.

Just to put this in context, there's 2 scripts running in parallel, one training and one measuring the iterations, once a new iteration is created it's graded, if it finds a new best score i run `trains.update_output_model` to point to the best model.

**Comment by bmartinn** [comment]
>Just to put this in context, there's 2 scripts running in parallel, one training and one measuring the iterations, once a new iteration is created it's graded, if it finds a new best score i run trains.update_output_model to point to the best model.

This is very cool! (In theory you could make it a distributed process, launch a Task to do the validation on another machine, like clone&enqeuue base Task that does inference then plug the results back to the training Task)

@rorph out out curiosity which framework are you using ?
