### ISSUE TITLE
Broken links in docs/trains_examples.md

### ISSUE THREAD

**Issue by NumesSanguis** [allegroai/trains#147]
The file `trains_examples.md` found here contains broken links after the documentation rework: https://github.com/allegroai/trains/blob/03fbfb8237af17531681a1a32a958f6fb2c1e108/docs/trains_examples.md

For example, `pytorch_tensorboard.py` refers to: https://github.com/allegroai/trains/blob/master/examples/pytorch_tensorboard.py
But the correct link (found here: https://allegro.ai/docs/examples/pre_refactoring/examples_pytorch/) should be: https://github.com/allegroai/trains/blob/master/examples/frameworks/pytorch/pytorch_tensorboard.py

**Comment by bmartinn** [comment]
Thanks @NumesSanguis , 
The examples.md is deprecated, I will make sure it is removed soon.
The updated version (still trying to keep up with the new additions to the examples folder) is on the documentation site (which is probably a better place for it)
https://allegro.ai/docs/examples/examples_overview/

**Comment by NumesSanguis** [comment]
Thank you for the link. Feel free to close this issue once examples.md is removed.

**Comment by bmartinn** [comment]
Thanks @NumesSanguis :)
`trains_examples.md` was removed, closing this issue.
