### ISSUE TITLE
Incorrect detection of git remote url path (ssh:// + domain)

### ISSUE THREAD

**Issue by devhello145** [allegroai/trains#149]
Failed to detect git remote repository 
See in `trains/backend_interface/task/repo/scriptinfo.py`:
`           repository=furl(repo_info.url).remove(username=True, password=True).tostr(),`

If repository url is ssh with domain, furl detects it incorrectly in particular `ssh://user_name@domain@servername/path_to_repo` and logged exception:
`trains.Task - WARNING - Failed auto-detecting task repository: Invalid host 'user_name@domain@server_name/path...' Host strings must have at least one non-period character, can't contain any of '!@#$%^&'"*()+=:;/', and can't have adjacent periods.`

**Comment by bmartinn** [comment]
Hi @devhello145 
Could you post the exact ssh url (obviously remove confidential information) ?
Two @ at the url name is highly unorthodox ...
Could you also specify the OS version and the git version?

**Comment by devhello145** [comment]
I found a solution by using `\` in opposite to `@`.
See more: https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples (Login with passwords -> Domain users)

**Comment by bmartinn** [comment]
@devhello145 nice workaround!
Just in case we added a fix, should work with `trains==0.15.1` :)
