### ISSUE TITLE
UTC timestamp instead of local time in auto-generated description

### ISSUE THREAD

**Issue by michaelitvin** [allegroai/trains#152]
This is under experiment -> info:

![image](https://user-images.githubusercontent.com/5813969/85537328-89797780-b61c-11ea-8126-8149984a9097.png)

Local time is +3 hours, and that's the time that is used for all other clocks in the interface.

**Comment by bmartinn** [comment]
Hi @michaelitvin 
The comment is auto-generated by the *Trains* init process at runtime.
As a general rule of thumb, the system always stores UTC timestamps, and converts them to local time stamps in the UI.
Unfortunately this is actually text generated by the Trains agent, so the UI cannot convert it.
Maybe we can change the test to say UTC time (or the opposite to mention the local time zone)
What do you think?

**Comment by michaelitvin** [comment]
I think that the times should be displayed in all places consistently.
People are used to think in local times, so best would be to specify the
local time everywhere. If that's not possible then at least state
explicitly that this is UTC.
It could also make sense to add a timezone configuration, so if the client
and server run in different timezones the times would still be displayed
consistently.

**Comment by bmartinn** [comment]
>It could also make sense to add a timezone configuration, so if the client
and server run in different timezones the times would still be displayed
consistently.

Time zone is take from your browser, so hopefully this should be taken care of :)

> . If that's not possible then at least state explicitly that this is UTC.

That makes sense, do you feel like PR-ing it (see [here](https://github.com/allegroai/trains/blob/577c0a3c4196d9ed3630a081e6e16bde42a13de1/trains/backend_interface/task/task.py#L303)) ?

**Comment by michaelitvin** [comment]
Forking and going through the entire PR process is a bit much for such a small change...

So if someone gets to this, it looks like the solution is just to add `'UTC'` to the string in [this line](https://github.com/allegroai/trains/blob/577c0a3c4196d9ed3630a081e6e16bde42a13de1/trains/backend_interface/util.py#L47).

Hope I'll get more chances to help later on:)

**Comment by bmartinn** [comment]
@michaelitvin the fix is avilable in the latest RC:
```bash
pip install trains==0.15.2rc0
```
