### ISSUE TITLE
Saving general artifacts

### ISSUE THREAD

**Issue by kfir99** [allegroai/trains#153]
Hi,
I'd like to save an object of a class I implemented as an artifact.
According to the documentation, it seems like something I am supposed to be able to do, but when I try I get an error:
"Artifact type <my_class> not supported" :(
Any ideas?

Thanks!

**Comment by bmartinn** [comment]
Hi @kfir99,
Wow that sounds quite cool!
Currently the upload_artifact method supports files (either as string or Path) or a set of predefined objects (Numpy,Pandas PIL Image etc.)

This is very interesting use case, could you elaborate on how it is used ?
Also, how would you do that (i.e. serialize the object), would it be to json it? pickle it?

**Comment by kfir99** [comment]
I'll elaborate:
I use gluoncv which is based on mxnet, and I have a "classification_network" class which includes a gluoncv network and some other information (synsets, etc...) which is the class I'm trying to save.
I usually pickle it to save locally, but any serialization method is fine for me.
Ideally I'd like to use this to log the model after every epoch - have the object of the classification_network class along with its accuracy and the epoch number

**Comment by bmartinn** [comment]
@kfir99 , let me see if I understand you correctly
1) Log the `classification_network` network.
2) Make sure that the output model is "connected" with the `classification_network` object, in order to have full visibility and traceability on the model weights, and how they were trained.

Regarding (1) you could do:
```python
import pickle
with open('temp_object.pkl', 'wb') as f:
    pickle.dump(my_object, f)

task.upload_artifact('classification_network', artifact_object='temp_object.pkl', delete_after_upload=True)
```

Regrading (2), you can manually upload a model file (which will be automatically connected with the experiment) :
```python
from trains import OutputModel
OutputModel(framework='mxnet').update_weights('mxmodel.bin')
```

What do you think?

**Comment by kfir99** [comment]
Thanks for your response!
The feature you suggested sounds very useful :)
I tried implementing your suggestions, (2) worked, but for (1) I got the same "artifact not supported" error, this time for <type 'str'>.
Am I missing something?

**Comment by bmartinn** [comment]
>The feature you suggested sounds very useful :)

@kfir99 , awesome we are in agreement, we will add this feature :rocket: 

> (1) I got the same "artifact not supported"

Notice that (1) passes a string (or a Path object) , My guess is that you passed a link to a file that was not there (or maybe it was a relative path etc).
You can verify with:
```python
from pathlib2 import Path
import pickle
with open('temp_object.pkl', 'wb') as f:
    pickle.dump(my_object, f)

pickle_file = Path('temp_object.pkl')
assert pickle_file.exists()
task.upload_artifact('classification_network', artifact_object=pickle_file, delete_after_upload=True)
```

**Comment by kfir99** [comment]
Changing the path from a string to a Path object worked :)
Thank you very much for your help!

**Comment by bmartinn** [comment]
Hi @kfir99 
You will be happy to hear that there is now support for auto pickling artifacts, and yes this is all thanks to you :)
```python
task.upload_artifact('MyObject', artifact_object=object() auto_pickle=True)
# and later from another process
my_object = task.artifacts['MyObject'].get()
```

Install the latest RC to enjoy the new feature
```bash
pip install trains==0.15.2rc0
```

**Comment by kfir99** [comment]
Thank you very much, I'm excited to try it out!
