### ISSUE TITLE
Slow task initialization

### ISSUE THREAD

**Issue by eladrich** [allegroai/trains#154]
Hi,
I'm using (and enjoying) trains on an on-premise server we deployed using docker-compose.
I've noticed that for some projects the Task.init function takes up to two minutes, any idea what can cause that?

From simple profiling it seems like most of the time is from the call to connect() -> _new_conn() -> create_connection() -> getaddrinfo() -> _socket.getaddrinfo()

Thanks!

**Comment by bmartinn** [comment]
Hi @eladrich 
Yes I do think that 2 Minutes is way too much! (and especially when this is an on-prem server, so connection should not be an issue)

>From simple profiling it seems like most of the time is from the call to connect() -> _new_conn() -> create_connection() -> getaddrinfo() -> _socket.getaddrinfo()

Thank you for the profiling!
One question, where is the `_new_conn` call coming from ? I could not locate it in the code base?
Also, whats the *trains* package version and the OS running the python code (the one calling Task.init())?

**Comment by eladrich** [comment]
Hi!
Thanks for the quick answer, looks like the connect() function I was looking at is inside urlllib which was triggered from trains send_request() function.

I'm using trains 0.15.1 (updated today, but not a new problem) with python 3.6.9, running inside an Ubuntu docker machine.

**Comment by bmartinn** [comment]
Hi @eladrich 
A few followup questions to allow me to better understand whether this is a client issue or a server issue:
The first call to the server takes the key/secret and creates a token to be used for the rest of the session.
The process of creating this token might take a second on the server side, but should definitely not be 2 minutes ...

- Is the first send_request() ? Are other send_requests() also as slow?
- Any chance you have another machine running with the same *trains-server* exhibiting the same slow initialization process?

**Comment by eladrich** [comment]
Took us some time, but we finally figured out the problem. It seems like some of our dockers had a faulty DNS configuration resulting in each request to the trains server to take 15 seconds to resolve. 

Fixed that and now initializes in 3 seconds 😎
