### ISSUE TITLE
how to remove the release notes from the log

### ISSUE THREAD

**Issue by chloe-wang** [allegroai/trains#157]
Hi,

is there a way to remove the release notes from the log when i'm not using the latest version?

**Comment by bmartinn** [comment]
Hi @chloe-wang ,

Hmm, well obviously you should upgrade :smile: 
Nothing to worry about, everything is backwards compatible, for example you can have *trains* 0.15.1 work with *trains-server* 0.14.x without any issues.
Does that help?

P.S.
If you feel strongly about it, we can have a flag in `trains.conf` disabling the warning.
What do you think?

**Comment by chloe-wang** [comment]
@bmartinn  thanks. Could you specify how to set the flag in the trains.conf to disable the warning? thanks a lot!

**Comment by chloe-wang** [comment]
Hi @bmartinn,

I feel we should have a flag in the trains.conf to disable the warnings. In my case, I have lots of conda envs with trains installed, and i don't want to update the trains for all of them. So it will be great if we have a flag in the trains.conf.

thanks a lot!

**Comment by bmartinn** [comment]
@chloe-wang, sure let's add that.
How about ?

```
# If set to True, *trains* update message will not be printed to the console
# this value can be overwritten with os environment variable TRAINS_SUPPRESS_UPDATE_MESSAGE=1
sdk.development.suppress_update_message = False
```

**Comment by bmartinn** [comment]
Hi @chloe-wang ,
:rocket:  The feature was added to *Trains*. You can now set `sdk.development.suppress_update_message=true` in your `~/trains.conf` to [suppress update messages](https://github.com/allegroai/trains/blob/0328327b5a0d991e4432917d2cbeea8e7eca1ed5/docs/trains.conf#L162).

Available in the latest RC version:
```bash
pip install trains==0.15.2rc0
```

**Comment by chloe-wang** [comment]
hi @bmartinn,

That's great! thank you so much!
