### ISSUE TITLE
Failed to use local server: "failed to locate provided credentials" error

### ISSUE THREAD

**Issue by antklen** [allegroai/trains#158]
I deployed local trains server according to this page https://allegro.ai/docs/deploying_trains/trains_server_linux_mac/, and it looks like it works fine. Then I make configuration with trains-init, and again it looks totally fine.
But immediately after that I'm receiving following error with simple `Task.init()` command:
> Action failed <401/22: projects.get_all/v1.0 (Unauthorized (invalid credentials) (failed to locate provided credentials))>

Tried several times to make new credentials and insert them in trains.conf file manually, but got the same error.
Can't find any tip how to solve this problem =(

![Screenshot from 2020-06-29 15-32-20](https://user-images.githubusercontent.com/9253973/86006294-6e44a880-ba1e-11ea-9e68-4e6e49bd2f71.png)

**Comment by bmartinn** [comment]
Hi @antklen 
Thanks for the screen-garb that really helps!
I suspect it is trying to fetch the previous Task (from the cache) which was probably executed on the demoapp server, and it fails...
Try removing this folder `~/.trains/` (it is the cache folder of *trains*)
If it solved the problem, I think I know where the bug is, if it did not, we will keep digging :)

**Comment by antklen** [comment]
Hi @bmartinn 
Thank you for your answer!
I tried to remove folder `~/.trains/`, but it didn't help. I tested demoapp server, but after I had this error with local server.

Then I tried to do the same thing on another machine (deploy local server and run `Task.init()`), and there everything works well.

Before I started trains server, I had another server on port 8080 (wandb). Not sure if this could cause the problem. But I tried to clear some more cache, reinstall trains - still doesn't work.

**Comment by antklen** [comment]
But I tested web UI of demoapp server (without running any code) before starting local trains server, could it cause the problem?

**Comment by bmartinn** [comment]
@antklen let's make sure the services are running:
To test the web UI, just browse to `http://localhost:8080` , if you can login and see your projects, it is all working well.
To test the backend RestAPI run `curl http://localhost:8008` it should reply with a json style result.

**Comment by antklen** [comment]
web UI is working well, and response to `curl http://localhost:8008` is
![Screenshot from 2020-06-30 20-21-21](https://user-images.githubusercontent.com/9253973/86157014-703a6480-bb0f-11ea-9622-d20c6ddabdba.png)

**Comment by bmartinn** [comment]
@antklen great, this means your server is up and running and working correctly :)

Now assuming you are running your code on the same machine as server.
Your `~/trains.conf` should have a section looking something like this one:
```
api {
    web_server: http://localhost:8080
    api_server: http://localhost:8008
    credentials {
        "access_key" = "KEY"
        "secret_key" = "SECRET"
    }
}
```

If you wonder how to get the Key/Secret, go to http://localhost:8080/profile and click the "create new credentials" button.
Once this is setup, you should be able to open your ipython and run:
```python
from trains import Task
task = Task.init('examples', 'my auth test')
```

**Comment by antklen** [comment]
@bmartinn Yes, I have this lines in `~/trains.conf`. I tried several times to generate new credentials and to copy them into `~/trains.conf` by hand or generate this file with `trains-init`, no changes.

Is there any way to check credentials in python script or via command line? I mean check exact values of access_key and secret_key entered by hand?

**Comment by antklen** [comment]
On profile page in web UI there is information that credentials were used:
![Screenshot from 2020-07-02 11-35-49](https://user-images.githubusercontent.com/9253973/86336239-4771b680-bc58-11ea-9d26-a45e789c70c2.png)

**Comment by bmartinn** [comment]
@antklen when you add the credentials using `trains-init` it verifies them with the *trains-server*.
That said, based on the screen grab you attached, it seems like both generated credentials were never used ...

1. Could you change the `localhost` to your machine IP (temporarily, just so we  could better debug it), 
it should look something like (obviously change th1 192.168.1.2 to the actual IP address):
```
api {
    web_server: http://192.168.1.2:8080
    api_server: http://192.168.1.2:8008
    credentials {
        "access_key" = "KEY"
        "secret_key" = "SECRET"
    }
}
```

2. Maybe the $HOME folder is not stable?! (for example running the trains-init from one user and the code from another?) ... could you test with the following code
(notice we change the os environment **before** importing the trains package)
```python
import os
os.environ['TRAINS_CONFIG_FILE'] = `/home/user/trains.conf`
from trains import Task
task = Task.init('examples', 'auth test')
```

**Comment by bmartinn** [comment]
@antklen did you manage to solve the issue?

**Comment by antklen** [comment]
Hi @bmartinn!

Sorry for late response, I wasn't able to work on issue for some time.
Your solution #1 works! Problem disappeared after I changed `localhost` to my machine IP.

Do you know what is the reason for such behavior?

**Comment by bmartinn** [comment]
Hi @antklen , this usually happens when working inside VMs (`localhost` is the network adapter of the VM and not the host running the service), sometimes this is firewall configuration issues...
Anyhow, we should probably add it to the FAQ, as I remember a few more questions regrading the same issue :)

**Comment by antklen** [comment]
I don't use VM, may be firewall or something else in my case.

Thanks a lot for your help!
