### ISSUE TITLE
Can't set status of a Failed task

### ISSUE THREAD

**Issue by michaelitvin** [allegroai/trains#159]
For `Aborted` tasks, I can do:
```
task = Task.get_task(task_id='...')
task.mark_started()  # either
task.completed()  # or
```

But for `Failed` tasks this has no effect.

**Comment by bmartinn** [comment]
Hi @michaelitvin 
Yes, failed tasks should not be "continued" but reset, and then rerun (because they failed, so why would you continue to use them...)
So this is the theory, and this is why it has no effect.
That said, if you really want, you can forcefully change the status to started.
```python
task = Task.get_task(task_id='aabbcc123')
from trains.backend_api.services import tasks
task.send(tasks.StartedRequest(task.id, force=True), ignore_errors=True)
```

Maybe we could have it as a parameter for `task.mark_started()`...

**Comment by michaelitvin** [comment]
Great that there's a workaround.

As far as I understand,Trains decides that a task has failed due to death of the process.
This means that if there's a power outage, the task will be Failed - though I would just continue it from the last saved checkpoint.

**Comment by bmartinn** [comment]
@michaelitvin , failed status will be the outcome of process exit code != 0 (exception raised, core dump etc.)
If for any reason the processed stopped reporting (e.g. machine goes down / restarts etc.) the *trains-server* watchdog will set the Task to "aborted" .

>This means that if there's a power outage, the task will be Failed - though I would just continue it from the last saved checkpoint.

Did you actually get a failed status ?

**Comment by michaelitvin** [comment]
I see... Well my specific usecase was that a colleague of mine `kill`ed the
process because he needed the GPU.

**Comment by bmartinn** [comment]
@michaelitvin ,  may I suggest using [trains-agent](https://github.com/allegroai/trains-agent) to schedule jobs, detect free GPU's etc :)

**Comment by michaelitvin** [comment]
In an ideal world yes:)
We're not there yet...

>

**Comment by bmartinn** [comment]
Hi @michaelitvin ,
You can now directly [force](https://github.com/allegroai/trains/blob/0328327b5a0d991e4432917d2cbeea8e7eca1ed5/trains/task.py#L1027) a status change on a task:
```python
task.mark_started(force=True)
```

Available in the latest RC:
```bash
pip install trains==0.15.2rc0
```
