### ISSUE TITLE
How can I remove an experiment from the project?

### ISSUE THREAD

**Issue by SunskyF** [allegroai/trains#16]
How can I remove an experiment from the project?
Sorry to bother you, but I can't find the way to remove an experiment after some tries.
I only find the way to delete a project.
Thanks a lot!

**Comment by bmartinn** [comment]
Yes, just move to archive (right click archive)

**Comment by SunskyF** [comment]
Thanks a lot!

**Comment by ktobah** [comment]
Any updates on this feature?

**Comment by bmartinn** [comment]
Hi @ktobah 
We added a cleanup services that takes archived experiments and deletes them after X days.
(This way users do not accidentally delete tasks, while we still keep the archived "folder" relatively clean)
You can check the cleanup service [here](https://github.com/allegroai/trains/blob/master/examples/services/cleanup/cleanup_service.py)

BTW:
You can always delete specific tasks from code:
```python
from trains.backend_api.session.client import APIClient
client = APIClient()
client.tasks.delete(task=task.id, force=True)
```

**Comment by ktobah** [comment]
Thank you very much, I think using the API call can do it for me.
