### ISSUE TITLE
Bad link for Confusion matrix example script

### ISSUE THREAD

**Issue by vfdev-5** [allegroai/trains#164]
Hi,

Example script's URL for [Confusion matrix docs](https://github.com/allegroai/trains/blob/master/docs/logger.md#confusion-matrices) ends with 404 error. Bad location is https://github.com/allegroai/trains/blob/master/examples/manual_reporting.py

**Comment by bmartinn** [comment]
Thanks @vfdev-5 ,
The logger.md is deprecated, I'll make sure we link to the documentation site, and remove the logger.md

**Comment by bmartinn** [comment]
@vfdev-5 , the documentation fix was pushed :)
Thanks again!

**Comment by vfdev-5** [comment]
Thanks for the update. I close the issue as solved for me :)
