### ISSUE TITLE
how to connect on-premise trains server

### ISSUE THREAD

**Issue by deepankar27** [allegroai/trains#166]
How can I connect & run my code on premise trains server?

As per example:
```
from trains import Task

task = Task.init(project_name="examples", task_name="scikit-learn joblib example")
```
But what we have to in case it's a on-premise?

**Comment by ainoam** [comment]
Hi @deepankar27,

The different configuration options of directing Trains to your on-prem server are covered [here](https://allegro.ai/docs/deploying_trains/trains_config_for_trains_server/) in the Trains documentation.

In short, use the Profile page in your own Trains Server UI to generate access credentials, and copy those details to your trains.conf configuration file.

**Comment by deepankar27** [comment]
@ainoam  Thanks..!!
