### ISSUE TITLE
Feature request: Random seed

### ISSUE THREAD

**Issue by eliorc** [allegroai/trains#167]
Reproduciblity is as we all know very important - in trains it is very easy to re-run a task when clicking.
Jointly with its auto-magical features, I think it would be awesome if it would automatically log (and even randomly set) the random seeds used by the various frameworks so reproducing will be down to the initial weights.

**Comment by JDennisJ** [comment]
Hi @eliorc ,

How about [make_deterministic](https://github.com/allegroai/trains/blob/2f5b519cd8c4df9d3db397604f5b8097c23ccc40/trains/utilities/seed.py#L10), can this do the trick?

When you start a task, the task object is using it with the default seed, 1337, but you can control it.

**Comment by eliorc** [comment]
Seems exactly what I was interested in - when searching for the keywords "seed" or "random seed" in the docs, I haven't found anything - that is why I opened this issue

**Comment by JDennisJ** [comment]
We can certainly add a brief about it, thanks for the feedback 😄
