### ISSUE TITLE
Tracking specific environment variables

### ISSUE THREAD

**Issue by eyalto** [allegroai/trains#17]
Is there a way to provide a default list of environment variables that are not part of args that are tracked along with the experiment ? 
If not can you add this as feature request ?

**Comment by bmartinn** [comment]
@eyalto thank you for the feature suggestion.
Here is what I was thinking:

`$ export TRAINS_LOG_ENVIRONMENT=`
(default) *TRAINS* does not log OS environment variables

`$ export TRAINS_LOG_ENVIRONMENT="PWD,PYTHONPATH"`
Will result in *TRAINS* logging values of both PWD and PYTHONPATH

`$ export TRAINS_LOG_ENVIRONMENT="*"`
Will result in *TRAINS* logging values of ALL environment variables

Is that what you had in mind?

**Comment by eyalto** [comment]
This is even better than what I was thinking about

Will this be applied soon ?

**Comment by bmartinn** [comment]
@eyalto, the feature is included in the latest release v0.10.2 exactly as [suggested](https://github.com/allegroai/trains/issues/17#issuecomment-507398767).

**Comment by shaulimaya** [comment]
Hey!
Thanks for the feature!
I already start using it, but I think that this is a little bit strange that the env params are under HYPER PARAMETERS
Maybe we can find other place for it?
Env params?

**Comment by bmartinn** [comment]
@shaulimaya great to hear you are already using this feature.
Yes, in the next version we will have a separate section for Environment Variables, until then they are under Hyper-Parameters.

**Comment by shaulimaya** [comment]
Thanks a lot!
Another small thing - if you can render links "http://blabla" as link
:)

**Comment by bmartinn** [comment]
@shaulimaya not sure security wise, this is recommended :)

**Comment by bmartinn** [comment]
Closing, feature is now available in 0.10.2
