### ISSUE TITLE
NotFittedError: This SGDClassifier instance is not fitted yet

### ISSUE THREAD

**Issue by shelikohan** [allegroai/trains#172]
Hey,
any ideas why I get this error?

clf = HungaBungaClassifier()
clf.fit(x_train, y_train)
clf.predict(x_test)

NotFittedError: This SGDClassifier instance is not fitted yet

I want to classify.
thanks :)

**Comment by bmartinn** [comment]
Hi @shelikohan 
I think I need some more information...
I'm assuming you are referring to [HungaBungaClassifier](https://github.com/ypeleg/HungaBunga), which sits on top of scikit learn.

What exactly are we trying to do here, get HungaBunga summary into *trains*? or is it about logging all the different models?
Any chance you can provide a toy code sample?

**Comment by shelikohan** [comment]
Thanks, Martin, already fixes it myself.
The problem was I entered categort type y_train/y_test array and not integers...

**Comment by bmartinn** [comment]
Hi @shelikohan , I'm closing the issue for now, if it resurfaces feel free to reopen.
