### ISSUE TITLE
use with yolo

### ISSUE THREAD

**Issue by Bakutto** [allegroai/trains#175]
good job! can i share with YOLOv4?

**Comment by bmartinn** [comment]
Thanks @Bakutto :)
What do you mean by "can i share with YOLOv4"?
Are you referring to a specific YOLOv4 implementation ?
Generally speaking any code will work, you just need to add:

```python
from trains import Task
task = Task.init('examples', 'YOLOv4 training')
```

If the code uses TensorBoard or Matplotlib all the metrics/graphs will be logged automatically.
If the code uses Keras/TF/PyTorch/Joblib the models will be logged as well.

**Comment by Bakutto** [comment]
Thanks a lot!
