### ISSUE TITLE
issue with GPU monitoring

### ISSUE THREAD

**Issue by Liranbz** [allegroai/trains#177]
Hi,
I use trains ai, and use args also.
here is my code for CUDA:

`parser.add_argument('--cuda',default=True,dest='cuda',action='store_true',help='Use cuda to execute model')
 device = torch.device("cuda:0" if (args.cuda and torch.cuda.is_available()) else "cpu")
`
 I run on CUDA but I got this msg:
**TRAINS Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring**

here is my monitor:

![image](https://user-images.githubusercontent.com/51919286/88845925-89593280-d1ed-11ea-8ceb-f5e349f25dca.png)

what I`m doing wrong?
Thanks

**Comment by bmartinn** [comment]
Hi @Liranbz 
> TRAINS Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring

This means *Trains* failed to access the nvidia .so/.dll to pull the GPU usage statistics (actually regradless of you using it, i.e. `torch.device` call :)

Which Trains version are you using?
What OS are you using?
Can you run `nvidia-smi` , does it return an active GPU?

**Comment by Liranbz** [comment]
Hi @bmartinn bmartinn 
My Trains version is: 0.15.1
OS: Windows 10
here is my `nvidia-smi` status while training a model
![image](https://user-images.githubusercontent.com/51919286/88924398-e3a0d480-d27b-11ea-892b-b7475e75ae03.png)

**Comment by bmartinn** [comment]
Hi @Liranbz 
I think there was a fix to the GPU monitoring in the latest RC (might apply here),
Could you test with
```bash
pip install trains==0.15.2rc0
```

**Comment by Liranbz** [comment]
Hi @bmartinn ,
I installed the new version. While running I got this massage:
```
2020-07-31 15:58:29,968 - trains.Task - ERROR - Action failed <400/122: tasks.set_requirements/v1.0 (Task is missing expected fields (Task has no script field): task=61fb9ceea7f34825840ad9b52f3a0ef1)> (task=61fb9ceea7f34825840ad9b52f3a0ef1, requirements={'pip': ''})
TRAINS Task: overwriting (reusing) task id=61fb9ceea7f34825840ad9b52f3a0ef1
2020-07-31 15:58:32,608 - trains.Task - INFO - No repository found, storing script code instead
TRAINS Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring
```

**Comment by bmartinn** [comment]
Hi @Liranbz 
Regrading the log error, the first bug is fixed and will be deployed in the next trains-server release (due in a week)

Regrading the missing GPU monitoring, this is very strange... 
Could you test with the [pynvm](https://github.com/gpuopenanalytics/pynvml) package, (*trains* relies on it for the GPU access)

```bash
pip install pynvml
```

Then in python
```python
from pynvml.smi import nvidia_smi
nvsmi = nvidia_smi.getInstance()
nvsmi.DeviceQuery('memory.free, memory.total')
```

**Comment by Liranbz** [comment]
Hi @bmartinn 

I did it and got this error:

```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pynvml\nvml.py", line 731, in _load_nvml_library
    nvml_lib = CDLL(os.path.join(os.getenv("ProgramFiles", "C:/Program Files"), "NVIDIA Corporation/NVSMI/nvml.dll"))
  File "C:\Program Files\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/liran_bz/PycharmProjects/BERT/test.py", line 3, in <module>
    nvsmi = nvidia_smi.getInstance()
  File "C:\Program Files\Python36\lib\site-packages\pynvml\smi.py", line 389, in getInstance
    nvidia_smi()
  File "C:\Program Files\Python36\lib\site-packages\pynvml\smi.py", line 404, in __init__
    nvidia_smi.__handles = nvidia_smi.__initialize_nvml()
  File "C:\Program Files\Python36\lib\site-packages\pynvml\smi.py", line 409, in __initialize_nvml
    nvmlInit()
  File "C:\Program Files\Python36\lib\site-packages\pynvml\nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "C:\Program Files\Python36\lib\site-packages\pynvml\nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "C:\Program Files\Python36\lib\site-packages\pynvml\nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Exception ignored in: <bound method nvidia_smi.__del__ of <pynvml.smi.nvidia_smi object at 0x0000013FD2F9A0F0>>
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pynvml\smi.py", line 421, in __del__
  File "C:\Program Files\Python36\lib\site-packages\pynvml\nvml.py", line 772, in nvmlShutdown
  File "C:\Program Files\Python36\lib\site-packages\pynvml\nvml.py", line 387, in get_func_pointer
pynvml.nvml.NVMLError_Uninitialized: Uninitialized
```

**Comment by bmartinn** [comment]
Hi @Liranbz 

Great, we found the problem.

Could you try to manually locate the file `nvml.dll`? this is what's needed in order to query the GPU.
Based on this [thread](https://forums.developer.nvidia.com/t/cant-find-nvml-dll-in-display-drivers/27648/4) it should be located here `"C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll"`, and that's where we look for it, but it seems that on your setup it is locate elsewhere. 

Let me know where you find the `nvml.dll`, I will make sure we add its directory to the search path.

**Comment by Liranbz** [comment]
Hi @bmartinn ,
I found the file in: `C:\Windows\System32`, and I moved it to `C:\Program Files\NVIDIA Corporation\NVSMI`, but actually I still got this error:

```
TRAINS Task: created new task id=*****************
2020-08-03 11:48:52,850 - trains.Task - INFO - No repository found, storing script code instead
TRAINS Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring
```

**Comment by bmartinn** [comment]
Hi @Liranbz 
Could you test again with `pynvml` ?

```python
from pynvml.smi import nvidia_smi
nvsmi = nvidia_smi.getInstance()
nvsmi.DeviceQuery('memory.free, memory.total')
```

**Comment by Liranbz** [comment]
Hi @bmartinn ,
Now these lines:
```
from pynvml.smi import nvidia_smi
nvsmi = nvidia_smi.getInstance()
nvsmi.DeviceQuery('memory.free, memory.total')
```
running well without errors. What to do next? Should I need to add these lines to my python script with trains? Or just run it once and that's it?

Thank you

**Comment by bmartinn** [comment]
Hi @Liranbz 
Okay, let's try this one:

```python
from trains.utilities.gpu import gpustat
print(gpustat.new_query().jsonify())
```

Let's see if this one works

**Comment by Liranbz** [comment]
Hi @bmartinn ,
I got this:

`{'hostname': 'OR', 'query_time': datetime.datetime(2020, 8, 3, 13, 51, 32, 712836), 'gpus': [{'index': 0, 'uuid': 'GPU-d31ec29c-91b6-af6e-111b-3fedbf6bb208', 'name': 'GeForce GTX 1080', 'temperature.gpu': 45, 'fan.speed': 26, 'utilization.gpu': 1, 'power.draw': 39, 'enforced.power.limit': 180, 'memory.used': 1018, 'memory.total': 8192, 'processes': '(Not Supported)'}]}
`

**Comment by bmartinn** [comment]
Hi @Liranbz 
I verified the bug, and a fix is on it's way 
I'll update here once an RC is out with the fix, should not take more than a week ;)

**Comment by bmartinn** [comment]
Hi @Liranbz ,
*trains* 0.16 was released, including a fix to the GPU monitoring issue on windows :)

**Comment by Liranbz** [comment]
Hi @bmartinn 
Thank you! I will try it!
