### ISSUE TITLE
Links from Getting Started Tutorial are broken

### ISSUE THREAD

**Issue by elimohl** [allegroai/trains#183]
https://allegro.ai/blog/setting-up-allegro-ai-platform/
It seems that examples are moved and some links became broken. See:
>Trains has got you covered (https://github.com/allegroai/trains/blob/master/examples/hyper_parameters_example.py)

>as well as storing general purpose artifacts (https://github.com/allegroai/trains/blob/master/examples/artifacts_toy.py)

**Comment by ainoam** [comment]
Thanks for pointing it out @elimohl - Seems like some housecleaning is order post refactor :)

The relevant code is now under:
https://github.com/allegroai/trains/blob/master/examples/reporting/hyper_parameters.py
and
https://github.com/allegroai/trains/blob/master/examples/reporting/artifacts.py

**Comment by ainoam** [comment]
@elimohl Updated the blog with the correct links - Thanks again!
