### ISSUE TITLE
New version noticed displayed after update

### ISSUE THREAD

**Issue by leonardbay** [allegroai/trains#185]
I just completed the update to version 0.16.0 following the instructions for data migration and then pulling a new docker-compose.yml file, etc. No errors were displayed during the process, the "Renaming the source directory..." message was displayed. After that, when accessing the web portal the message: "A newer version of trains-server ( 0.16.0) is available" is still being displayed. Is that expected or did I miss a step of the update process? Thank you!

BTW: there seems to be a broken link in "contributing guidelines": please check whether the bug you want to report already appears [here](link to issues

**Comment by leonardbay** [comment]
Some more information: the browser console and network tab complain about failing to retrieve a file named version.json.

**Comment by jkhenning** [comment]
Hi @leonardbay,

Thanks for reporting this issue. This is certainly not expected (assuming you reloaded the UI using either `Ctrl-F5` or using the `Reload` button in the update message).

We'll look into it and get back to you :slightly_smiling_face:

**Comment by jkhenning** [comment]
@leonardbay can you just go to the Profile page in the UI and see what is the reported server version?

**Comment by leonardbay** [comment]
Something strange is happening, now there are no more messages about the missing json file, but the message to update is still there. The trains-server is working from port 80 (not 8080) change made on docker-compose.yml, the address is: http://trains-server.eraniot.com/
Yes, I have hit refresh, hard-refresh, using Chrome with dev tools open and no cache.

**Comment by jkhenning** [comment]
And the reported server version in the Profile page?

**Comment by leonardbay** [comment]
Yes, I went to the profile page, which has changed position from bottom of left panel to upper right corner (indicating a version update), and it says: (0.16.0-299). In addition, now there's no message about a new version being available. So, it all seems to be working now, no idea why it didn't before. Thank you, for your excellent follow up!
