### ISSUE TITLE
UI Error: Unable to create credentials

### ISSUE THREAD

**Issue by rcox771** [allegroai/trains#190]
Hi 👋 I'm trying the on-prem/server deployment for trains through docker-compose and am getting a `Unable to create credentials` error when trying to customize my configuration through trains-init. Where would be a good place for me to start to debug this?
![image](https://user-images.githubusercontent.com/13604961/90451874-0fa8bc00-e0aa-11ea-97a5-e2277f272da8.png)

**Comment by jkhenning** [comment]
Hi @rcox771,

Start by opening your browser's developer tools (`F12`) and select the Network tab. Now, try to create credentials again and look at the request sent to the server (should appear as the last network request sent) - it should contain a more detailed error.

**Comment by rcox771** [comment]
@jkhenning I think I got it from here. Pretty sure I need to forward 8008 through my vpn. I'll close this for now thanks!
