### ISSUE TITLE
logger.report_text fails

### ISSUE THREAD

**Issue by alexgoft** [allegroai/trains#191]
I am trying to follow Explicit Reporting tutorial. How ever, when trying to run `pytorch_mnist_tutorial.py` it fails on the following line:

```
    logger.report_text('The default output destination for model snapshots and artifacts is: {}'.format(model_snapshots_path), level=logging.DEBUG)
```
logger was initialized via `logger = task.get_logger()` without any errors.

**Comment by JDennisJ** [comment]
Hi @alexgoft ,

Did you manage to solve the issue? If not, can I help you with that?
