### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by nirraviv** [allegroai/trains#196]
I have trains version 0.16.
The task recognizes my installed packages contain torch == 1.5.1+cu101 but after clone (or reset) it installs torch version 1.6.0. 
Any idea why and how can I fix this?

**Comment by bmartinn** [comment]
Hi @nirraviv 
Yes, that is odd.
`trains-agent` will install the correct torch version based on the installed CUDA drivers, that said it will not change the torch version but select the one compiled for the correct CUDA.
Could you attach the "original" "installed packages" list and the one updated after the `trains-agent` runs the experiment (i.e. after cloning the experiment and enqueuing it)?

**Comment by nirraviv** [comment]
Hi @bmartinn 
Thank you for the quick response.
Attached are the required lists. 
Note that `sbu_whispro_base` is an internal repo which do not have pytorch in its requirements.

In addition, `trains-agent` thought that my CUDA version is 10.0 (and thus installed torch 1.6.0+92) and setting `agent.cuda_version: 10.1` fixed this problem.
[actual_installed_packages.txt](https://github.com/allegroai/trains/files/5148882/actual_installed_packages.txt)
[original_installed_packages.txt](https://github.com/allegroai/trains/files/5148883/original_installed_packages.txt)

**Comment by bmartinn** [comment]
Hi @nirraviv 
I'm happy you managed to solve the issue, kudos!
That said you mention " my CUDA version is 10.0 (and thus installed torch 1.6.0+92)", on the face of it, this seems like a bug.
1. Can I assume `trains-agent` reported (starting up) "agent.cuda_version: 10.0" ?
2. From the attached logs, it seems the original packages are
torch == 1.5.1+cu101
torchvision == 0.6.1+cu101
But the installed, although say the wrong torch version, actually point to the correct wheel (see the link itself), in both cases CUDA 10.1 (cu101 -> cuda 10.1)
torch==1.6.0 # https://download.pytorch.org/whl/cu101/torch-1.5.1%2Bcu101-cp36-cp36m-linux_x86_64.whl
torchvision==0.6.1 # https://download.pytorch.org/whl/cu101/torchvision-0.6.1%2Bcu101-cp36-cp36m-

3. Are you running in virtual environment mode or docker mode ?

Could you verify that the installed package was actually 1.6.0 , and not when the link says (i.e. 1.5.1) ?

**Comment by nirraviv** [comment]
Hi @bmartinn 
1. Indeed it was `agent.cuda_version: 100` and now `agent.cuda_version: 101`
2. Even though it state the correct wheel it installs the following:
```
Collecting torch
Using cached torch-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (748.8 MB)
````
and as I send you the final pip state torch version is 1.6.0.
3. I'm currently running in virtual environment mode.

**Comment by bmartinn** [comment]
@nirraviv, could you send the initial part of the log of the experiment with the cuda 10.0 and the incorrect torch version (no need for the entire log, just up until the actual execution) ?

My theory is that although `trains-agent` downloaded the correct 1.5.1 version, some other package needed torch 1.6.0, and this is why there is a mix in the reported torch package, version being the actually installed one, and link to the downloaded one.

**Comment by nirraviv** [comment]
@bmartinn, attached are the initial part of the log for both experiments (before I changed cuda version and after).
As you can see, `pip` is the package manager.
[task_cu101.log](https://github.com/allegroai/trains/files/5157057/task_cu101.log)
[task_cu100.log](https://github.com/allegroai/trains/files/5157060/task_cu100.log)

**Comment by bmartinn** [comment]
Thanks @nirraviv .

1.
I just looked into the logs, the cu100.log is specifically asking for torch==1.6.0 from the beginning.
This implies that this was what you had on the Task "Installed Packages" section.
This is in contrast to the cu101.log which is trying to download the 1.5.1 version:
From the cu100 log:
```
Warning! Could not locate PyTorch version torch==1.6.0 matching CUDA version 100, trying CUDA version 92
1598537588568 ubuntu-magnus-4:gpu2 DEBUG Warning! Could not locate PyTorch version torchvision==0.6.1 matching CUDA version 100, trying CUDA version 92
Collecting torch==1.6.0+cu92
  File was already downloaded /home/nirr/.trains/pip-download-cache/cu100/torch-1.6.0+cu92-cp36-cp36m-linux_x86_64.whl
```
And at the end you have consistent package version / download link (even though not what you needed):
```
- 'torch==1.6.0 # https://download.pytorch.org/whl/cu92/torch-1.6.0%2Bcu92-cp36-cp36m-linux_x86_64.whl'
```

Could you verify the original Task had "torch==1.6.0" ?

2.
Now regrading the odd behavior of cu101.log:
From the log, what happens is we first install all the requested packages:

```
1598854176338 ubuntu-magnus-4:gpuall DEBUG Collecting torch==1.5.1+cu101
  File was already downloaded /home/nirr/.trains/pip-download-cache/cu101/torch-1.5.1+cu101-cp36-cp36m-linux_x86_64.whl
...
1598854322213 ubuntu-magnus-4:gpuall DEBUG Successfully installed GitPython-3.1.7 PyYAML-5.3.1 absl-py-0.10.0 attrs-20.1.0 cachetools-4.1.1 certifi-2020.6.20 chardet-3.0.4 cycler-0.10.0 funcsigs-1.0.2 furl-2.1.0 future-0.18.2 gitdb-4.0.5 google-auth-1.21.0 google-auth-oauthlib-0.4.1 grpcio-1.31.0 humanfriendly-8.2 idna-2.10 importlib-metadata-1.7.0 joblib-0.15.1 jsonschema-3.2.0 kiwisolver-1.2.0 markdown-3.2.2 matplotlib-3.2.2 oauthlib-3.1.0 orderedmultidict-1.0.1 pandas-1.0.5 pathlib2-2.3.5 pillow-7.2.0 playsound-1.2.2 plotly-4.9.0 protobuf-3.13.0 psutil-5.7.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 pydub-0.24.1 pyjwt-1.7.1 pyparsing-2.4.7 pyrsistent-0.16.0 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 requests-file-1.5.1 requests-oauthlib-1.3.0 retrying-1.3.3 rsa-4.6 scipy-1.5.0 seaborn-0.10.1 six-1.15.0 smmap-3.0.4 tensorboard-2.3.0 tensorboard-plugin-wit-1.7.0 
torch-1.5.1+cu101 torchvision-0.6.1+cu101
tqdm-4.47.0 trains-0.16.0 typing-3.7.4.3 urllib3-1.25.10 webrtcvad-2.0.10 werkzeug-1.0.1 zipp-3.1.0
```

Notice that the correct torch==1.5.1 is installed.
After that the `trains-agent` installs the git based repositories:
```
1598854327295 ubuntu-magnus-4:gpuall DEBUG Replacing original pip vcs 'git+ssh://codefront:22/tfs/DefaultCollection/CEVA_DEV/_git/sbu_whispro_base@853df8012ff44df6117dc7b81c36e7f9bda5e62c#egg=sbu_whispro_base' with 'git+ssh://codefront/tfs/DefaultCollection/CEVA_DEV/_git/sbu_whispro_base@853df8012ff44df6117dc7b81c36e7f9bda5e62c#egg=sbu_whispro_base'
Installing collected packages: sbu-whispro-base
...
Collecting torch
1598854337442 ubuntu-magnus-4:gpuall DEBUG   Using cached torch-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (748.8 MB)
...
ERROR: torchvision 0.6.1+cu101 has requirement torch==1.5.1, but you'll have torch 1.6.0 which is incompatible.
```

All leading me to the conclusion there is torch==1.6.0 in the requirement of the internal package you are installing.
Notice that at the end even in cu101.log case, you end up with torch==1.6.0 (and not 1.5.1)
Could you verify this theory?

**Comment by nirraviv** [comment]
@bmartinn 
1. I guess its my fault since I sent you a clone of a clone. Thus, in the original clone I see the following
```
Warning! Could not locate PyTorch version torch==1.5.1 matching CUDA version 100, trying CUDA version 92
```
just as in cuda 10.1
2.  I saw this odd behavior of installing torch 1.5.1 and then 1.6.0 but sbu_whispro_base requirements file includes the following:
```
pydub>=0.24.1
python_speech_features>=0.6
ptflops>=0.6.2
trains>=0.15.1
GitPython>=3.1.7
PyYAML>=5.3.1
scipy>=1.5.0
numpy>=1.19.0
pandas>=1.0.5
```
and now I see that ptflops has torch in its requirements without any version, so this is probably the problem. Thanks!

**Comment by bmartinn** [comment]
So I took a second look at the odd behavior caused by `ptflops`.
It turns out this actually points to a real bug, when installing a package from git, it will always reinstall the dependencies of said package (which, in our case, will cause `torch` to get reinstalled but without the original version limit).
I will make sure we fix it :)

**Comment by nirraviv** [comment]
I will remove it for now from my requirements but please update when fixed. Thank you @bmartinn !
