### ISSUE TITLE
Possibility to remove scalars / plots / debug samples

### ISSUE THREAD

**Issue by mhashas** [allegroai/trains#202]
Hi,

Thanks for the library. My use case is running a model multiple times with different seeds. I want everything to be reported under the same experiment. How I do it right now, assuming only accuracy scalar:

1) accuracy_seed_x
2) accuracy_seed_y, etc.

Once the training is finished, I average the results and report it under accuracy. Once I have done this, I would actually like to remove accuracy_seed_{x,y} to have fewer graphs. I create them so I can have some intermediate results to look at, but once it finished I actually want to discard them. This is a use case for cross-validation, I want to visualize separate folds, but once it finished I just want to look at the averaged results.

I would expect something like logger.delete_metrics(), logger.delete_plots() etc. Let me know if its currently supported or if there's some workaround. I assume I could have an accuracy_temp where I save the accuracy_seed_x. Once that finished, I overwrite it all with 0's. Then I start writing there accuracy_seed_y. Thanks!

**Comment by bmartinn** [comment]
Thank you @mhashas for the kind words :smiley: 
Are you running the cross-validation tests serially one after the other in the same experiment ?
Or are you looking for multiple runs reporting on the same external experiment (i.e. collecting all graphs of the multiple runs on a single experiment) ?

There is currently no API call to delete a specific metric, only all of them. 
Why is it important to delete them all once you are done?
You can always have another series named "average", and in the Web UI, if you double click on series in the graph legend, it will only present that specific series.

What do you think?

**Comment by mhashas** [comment]
Hi @bmartinn, thanks for the quick response. 

I am running the tests serially one after the other in the same experiment. The reason is that I want to have the graphs of the multiple runs on the same experiment. 

To highlight the reason why it is important, imagine that I am reporting per task 5 scalars, i.e. accuracy, balanced accuracy, etc. My model predicts 5 of these tasks, which results in 25 scalars => 25 scalar graphs. If I want to run 5 experiments with different seeds and aggregate the results, assuming I underscore scalar names by seed, I would have 25*5=125 scalar graphs. In the end I will create average scalars => 25 average scalars => 25 average scalar graphs. The last 25 are the only one I am interested once training finished, the previous 125 are good for intermediate visualization. So it would be nice for me to be able to clean up the graphs and delete the unused 125 once I am finished. The workaround that I have now is that for each seed I aggregate the results under `scalar_name_temp` and then after 1 seed I reset the graph by putting 0's everywhere, so the next seed can reuse it. 

Regarding using the UI to only present that specific series, I agree with you, but it would also be nice if I can clean-up intermediate results that I am plotting. 

Regards,
Radu

**Comment by bmartinn** [comment]
Hi @mhashas 
Apologies for the delay, this one somehow slipped away :(

So two options:
1. As you already mentioned, you can overwrite the scalars every new seed, and your `scalar_name_temp` is exactly that :)
2. You can create a "dummy" experiment, actually containing the results for the specific seed.
Once you are done, you can reset the experiment (thus deleting all its scalars), and reuse it.
Finally you can delete the "dummy" experiment altogether
```python
# create dummy task
dummy = Task.create('examples', 'dummy')
# report metric
dummy.get_logger().report_scalar(...)
# new seed, clear dummy task
dummy.reset(set_started_on_success=False, force=False)
# when done, delete task
dummy.close()
from trains.backend_api.session.client import APIClient
client = APIClient()
client.tasks.delete(task=dummy.id)
```
