### ISSUE TITLE
Highest score in all itterations support

### ISSUE THREAD

**Issue by evolu8** [allegroai/trains#21]
If I store a value and list it in my columns I can search/order by it. e.g. Overall_AUC. This is good. However it does not use the highest score (just the last one made I think). Which is not good. I can work around this with code (updating a 'best_AUC' value whenever it improves within a session. So low priority. But it will be a common UX usecase I think.

**Comment by bmartinn** [comment]
@evolu8 you are absolutely correct, this will be fixed in future versions. We will allow to select last/high/min per value. Until then, your solution sounds like a neat workaround.

**Comment by bmartinn** [comment]
Forgot to update here, v0.11 of trains-server is out :tada: with this feature added!
@evolu8 I hope that this is what you were looking for...

**Comment by bmartinn** [comment]
Closing, feature added.
