### ISSUE TITLE
Color channel order in debug images with TensorBoardX

### ISSUE THREAD

**Issue by S-aiueo32** [allegroai/trains#22]
I'm using TRAINS without any changes of the codes written with PyTorch+TensorBoardX.
It almost works well, however, debug images have different color channel order from TensorBoardX's one, i.e. BGR.
Considering compatibility between torchvision and PIL, I think it should be RGB.

**Comment by bmartinn** [comment]
@S-aiueo32 could you send specific package versions and if possible a short code snippet to reproduce the problem.

**Comment by S-aiueo32** [comment]
You can reproduce this issue like below.
```python
from PIL import Image
from torchvision.transforms import functional as TF
from tensorboardX import SummaryWriter

from trains import Task
task = Task.init(project_name='hoge', task_name='fuga', reuse_last_task_id=False)

image = Image.open('../data/Set5/HR/head.png').convert('RGB')
image = TF.to_tensor(image)

writer = SummaryWriter()
writer.add_image('image', image, global_step=0)
writer.close()
```

TensorBoard displays correctly:
![individualImage (1)](https://user-images.githubusercontent.com/14917234/61186142-f1011600-a69c-11e9-8aa4-1d4e45b28f3f.png)

TRAINS shows a different result:
![Images_image_00000000](https://user-images.githubusercontent.com/14917234/61186161-27d72c00-a69d-11e9-9050-1a891d4b42c9.jpeg)

**Comment by S-aiueo32** [comment]
My package versions here:
```
Pillow-SIMD==6.0.0.post0
torch==1.1.0
torchvision==0.2.2.post3
tensorboardX==1.8
tensoboard==1.14.0
trains==0.10.2rc2
```

**Comment by bmartinn** [comment]
Awesome, thanks! I'll keep you posted regrading a fix.

**Comment by bmartinn** [comment]
Fixed :)
Let me know if the problem consists
`$ pip install trains==0.10.2`

**Comment by S-aiueo32** [comment]
I confirmed, Thanks!
