### ISSUE TITLE
Login error when testing on demo server

### ISSUE THREAD

**Issue by laurent3577** [allegroai/trains#228]
I have been using Trains for the last few weeks and everything was working perfectly using the demo server. However I started getting this error now though haven't changed anything to my code / environment: 

`trains.backend_api.session.session.LoginError: Failed getting token (error 401 from https://demoapi.trains.allegro.ai): Unauthorized (invalid credentials) (failed to locate provided credentials)`

Not sure how to solve this issue.

**Comment by jkhenning** [comment]
Hi @laurent3577 ,

The demo server is reset every week, which may invalidate your generated credentials (which you've configured using `trains init` or manually in your `trains.conf`), as all data from the server including demo users is cleared.

If you wish, you can simply log into the demo server's UI and generate a new pair of credentials. Please note, though, that this may occur again in the next demo server reset (all the more reason to install your own copy of the Trains Server 🙂 )

**Comment by laurent3577** [comment]
Wonderful! It had not happened after the previous resets so I didn't think it was related to that. Now it works perfect again. For now I'm only using it for some toy projects but would definitely use my own trains server for more serious work.
