### ISSUE TITLE
Running fc-solve's py-trains-test.py does not yield any result after a > 6 hours wait

### ISSUE THREAD

**Issue by shlomif** [allegroai/trains#23]
Hi! After I run this program - https://github.com/shlomif/fc-solve/blob/10dd2f6e756a51bbd0b24d680d03e3eec40da5cb/fc-solve/scripts/py-trains-test.py , a record for it is created on the test server, but without any result after a more than 6 hours wait. Note that getting it to run is likely still a bit involved, but I'll work on making it easier.

**Comment by shlomif** [comment]
OK, I simplified getting the program to run on the git master branch. Now I will work on a docker program.

**Comment by shlomif** [comment]
See https://github.com/shlomif/fc-solve/blob/master/fc-solve/scripts/docker--py-trains.pl for getting the program to run.

**Comment by bmartinn** [comment]
I looked at the code, what exactly are you expecting to see while running it (other than of course the std output)? 
I could not detect a Tensorboard or matplotlib graph being used, but I might have missed it.

**Comment by shlomif** [comment]
> I looked at the code, what exactly are you expecting to see while running it (other than of course the std output)?

I generates initial [freecell](https://en.wikipedia.org/wiki/FreeCell) [ms deals](https://fc-solve.shlomifish.org/faq.html#what_are_ms_deals) and solves them using a fast-on-average search and emits the moves of the solution. See https://fc-solve.shlomifish.org/faq.html for more info. I hope to get some insights about an algo to solve freecell, or at least some recommendations for improvement.

> I could not detect a Tensorboard or matplotlib graph being used, but I might have missed it.

I did not use them. Should I?

**Comment by bmartinn** [comment]
You  mentioned:
>  a record for it is created on the test server, but without any result after a more than 6 hours wait. 

How is this record (I assume a file) created? Are you using Tensorflow/Keras/PyTorch?
These are currently the supported frameworks, where *Trains* auto-magically detects/registers/upload a model file.

**Comment by bmartinn** [comment]
@shlomif I think there is a bit of a misunderstanding on what _TRAINS_ was built for.
_TRAINS_ is all about experiment versioning and auditing, and it achieves its "almost zero" integration by connecting to a predefined list of frameworks (currently TensorFlow/Keras/PyTorch/Matplotlib/SeaBorn etc.).

When used with other/custom code, what you can expect from out-of-the-box usage is:
Log of git commits (and git diff)
Log of used python packages

All the rest, i.e. graphs, model auditing etc. relies on the use of these frameworks, since in your case it is all custom code, I can't see how _TRAINS_ can magically add graphs and model auditing :)

That said, I would suggest you manually add a few graphs to your code, using matplotlib, and see how _TRAINS_ automatically adds them to your experiment logging.

I'm hoping it will be helpful in your algorithm optimization efforts.

**Comment by shlomif** [comment]
On Sat, 20 Jul 2019 14:30:26 -0700
"Martin.B" <notifications@github.com> wrote:

> @shlomif I think there is a bit of a misunderstanding on what _TRAINS_ was
> built for. _TRAINS_ is all about experiment versioning and auditing, and it
> achieves its "almost zero" integration by connecting to a predefined list of
> frameworks (currently TensorFlow/Keras/PyTorch/Matplotlib/SeaBorn etc.).
> 
> When used with other/custom code, what you can expect from out-of-the-box
> usage is: Log of git commits (and git diff)
> Log of used python packages
> 
> All the rest, i.e. graphs, model auditing etc. relies on the use of these
> frameworks, since in your case it is all custom code, I can't see how
> _TRAINS_ can magically add graphs and model auditing :)
> 
> That said, I would suggest you manually add a few graphs to your code, using
> matplotlib, and see how _TRAINS_ automatically adds them to your experiment
> logging.
> 
> I'm hoping it will be helpful in your algorithm optimization efforts.
> 

I see - thanks for the clarification. I'll see what I can do.

> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
What does “Zionism” mean? - http://shlom.in/def-zionism

The cool thing about Vim is — you find something interesting with every typo.
    — Su‐Shee on Freenode’s #perl .

Please reply to list if it's a mailing list post - http://shlom.in/reply .
