### ISSUE TITLE
[BUG] torch version defined in dependencies of a dependency is not processed

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains#234]
Hi,

If I have an experiment requiring the following:
- torch==1.3.1
- ...

Trains will correctly download the wheel from the matching torch/python/plateform/cuda version

Now if I have an experiment with the following requirements:
- library_requiring_torch
- ...

Where `library_requiring_torch` requires `torch==1.3.1`, 

It seems like trains will not catch the torch requirement and will not apply the logic to replace it by the corresponding wheel, resulting in the CPU version of torch being installed.

This can be simply fixed by always specifying the torch version in the experiment requirements, as shown here in the first case. I just wanted to document this bug somewhere if someone faces it in the future 👍

**Comment by bmartinn** [comment]
Thanks @H4dr1en !
Do we want to keep this issue open?

**Comment by H4dr1en** [comment]
Happy to close yes 👍
