### ISSUE TITLE
[Question] Disable logging?

### ISSUE THREAD

**Issue by sharkybe** [allegroai/trains#235]
hi all, 
I didnt find answers in documentation to my questions so I will be asking here. hope its ok.

my use-case is that i'm developing some ML script and i'm running it multiple times for debugging which I dont want to record, and only once in a while, I run an expirment which I want to record.
my questions is:
1. Is it possible to run a expirment without logging it in the dashboard? 
2. Is it possible to delete a expirment from the dashboard? (not archiving, but really deleting) 

Thanks

**Comment by JDennisJ** [comment]
Hi @sharkybe 

> Is it possible to run a expirment without logging it in the dashboard?

Once you are adding the `Task.init` line to your code, by default the experiment will be sent to the dashboard, but, when you run it locally, every run should override the last one (that's good for the case you are debugging an experiment and don't want any debug experiments).

> Is it possible to delete a expirment from the dashboard? (not archiving, but really deleting)

You can delete experiments, but not from the dashboard. Trains have a [cleanup service](https://github.com/allegroai/trains/blob/master/examples/services/cleanup/cleanup_service.py) that can do it for you (This service is configured to delete archived experiments and their accompanying debug samples, artifacts, and models older than 30 days, but you can change it). 
If you like to delete those with your script, you can use the APIClient, like [here.](https://github.com/allegroai/trains/blob/master/examples/services/cleanup/cleanup_service.py#L72)

**Comment by sharkybe** [comment]
Thankyou!
