### ISSUE TITLE
Default installation of opencv-python conflicts with existing opencv version

### ISSUE THREAD

**Issue by daganesh** [allegroai/trains#24]
**Description:** Trains automatically installs package opencv-python, which conflicts with existing opencv installations. Moreover this is not an official release (As quoted in PyPi.org: "Unofficial pre-built OpenCV packages for Python.")
Same might happen also for numpy installation.
**Problem:** new installation prevents us from using specific official opencv versions.
In our case it is even worse, as we build our own opencv from source code.
**Possible solutions:** 
1. Check if opencv is already installed before installing it
2. Remove opencv from requirements.txt and ask user to install manually

**Environment:**
Linux, Ubuntu 16.0.4. (using standard pip-install)
python 3.6
Opencv 4.0.1 (modified and locally built)
Trains v0.10.1

**Comment by bmartinn** [comment]
How about installing with:
`$ pip install --no-deps trains`

Then you can manually install manually the dependencies:

`$ pip install apache-libcloud attrs boto3 botocore funcsigs furl future google-cloud-storage humanfriendly jsonmodels jsonschema numpy pathlib2 pigar plotly psutil pyhocon python-dateutil pyjwt PyYAML requests-file requests six tqdm typing urllib3`

**Comment by daganesh** [comment]
Thanks for the quick reply, this is exactly what we did after struggling with opencv :)
Indeed we have opencv (which is rather standard) and not python-opencv (which is non-official, right?)

Nevertheless I would suggest documenting this issue in the installation guidelines.

Cheers

**Comment by bmartinn** [comment]
Thanks @daganesh, I will make sure it's added to the FAQ
