### ISSUE TITLE
Error when uploading keras models with trains==0.16.3

### ISSUE THREAD

**Issue by n-Guard** [allegroai/trains#253]
I get the following errors when keras models are being uploaded:

```
trains.storage - ERROR - Calling upload callback when starting upload: maximum recursion depth exceeded
trains.storage - INFO - Starting upload: /path/to/model.h5 => <FILESERVER-URL>/DefaultTemplate/train.59483bce57a64cf3ad936b72e9537c0b/models/model.h5
trains.storage - WARNING - Exception on upload callback: maximum recursion depth exceeded in comparison
```
Reproducible code: https://gist.github.com/n-Guard/c287822ae001f46172c82499a8328f8d
tf.keras==2.3.1
trains==0.16.3
This problem was not present in trains 0.16.2.

**Comment by bmartinn** [comment]
Thank you @n-Guard , The bug is verified (the code snippet was very helpful).

**Comment by bmartinn** [comment]
@n-Guard it is now fixed on the master, feel free to check with:
```
pip install git+https://github.com/allegroai/trains.git
```

**Comment by n-Guard** [comment]
Thank you very much, now everything works as expected!
