### ISSUE TITLE
hyperparameter search with optuna 

### ISSUE THREAD

**Issue by mhashas** [allegroai/trains#254]
Hi, 

I am trying to do hyper parameter search with optuna starting from this code https://github.com/allegroai/trains/blob/master/examples/optimization/hyper-parameter-optimization/hyper_parameter_optimizer.py. 

However, when playing with the learning rate for example, regardless if I use lr or --lr, it shows under general, not args and is not parsed by the command line arguments, i.e. not used. How can I integrate the most easily to have the hyperparameter search integrated with argparse with minimal code changes? What I assumed that it would happen is that the value for the lr parameter in args is going to be changed and the python method called.

![image](https://user-images.githubusercontent.com/13119609/99821323-3287b800-2b52-11eb-8d34-08e5e351f408.png)

![image](https://user-images.githubusercontent.com/13119609/99821450-5814c180-2b52-11eb-8b4a-ffa4ee829fc2.png)

**Comment by bmartinn** [comment]
Hi @mhashas 
1. In the base experiment (the one we will be trying to optimize), can you see any of your arguments?
Notice, if your code uses `argparse`, all the arguments will appear under the "Args" section.
If you connected parameters manually (i.e. with a call to `task.connect(my_dict)`) they will appear under the "General" section
2. In the HPO example, the name of the argument to optimize should match what you have in the UI 
(notice it is case sensitive, and there is no need to add extra `--` , it should be exactly as you see in the UI).
If I understand your example, it should be something like:
```python
an_optimizer = HyperParameterOptimizer(
    base_task_id=args['template_task_id'],
    hyper_parameters=[
        DiscreteParameterRange('Args/lr', values=[1e-05, 1e-04, 1e-03]),
    ],
    ...
```

**Comment by mhashas** [comment]
Hi @bmartinn,

Thanks so much for your response. Indeed number 2 is what I was looking for and it works as expected.

**Comment by mhashas** [comment]
Hi @bmartinn,

I have a follow-up question. I am trying to change the samplers and pruners used by Optuna

``
  an_optimizer = HyperParameterOptimizer(
        
        base_task_id=task_args['template_task_id'],
        hyper_parameters=hyper_parameters],
        objective_metric_title='linear_kappa_kl',
        objective_metric_series='val',
        objective_metric_sign='max',
        optimizer_class=OptimizerOptuna,
        max_number_of_concurrent_tasks=config.max_number_of_concurrent_tasks,
        time_limit_per_job=config.time_limit_per_job,
        pool_period_min=5,
        total_max_jobs=config.total_max_jobs,
        min_iteration_per_job=50,
        max_iteration_per_job=150,
        optuna_sampler=TPESampler(),
        optuna_pruner=HyperbandPruner())
``

However I get the error
``
ValueError: Only builtin types (str, int, str, float, list, tuple, dict, NoneType) are allowed for values (got General/opt/optimizer_kwargs/optuna_sampler=>TPESampler, General/opt/optimizer_kwargs/optuna_pruner=>HyperbandPruner)
``

I debugged through the source code a bit and if I disable auto_connect_task the HPO is instantiated. I don't fully understand what does auto_connect_task do and if I should disable it?

**Comment by bmartinn** [comment]
Hi @mhashas,
I think you are correct, this is a bug (of a sort), kudos on the workaround!

The HPO object connects its own configuration with the Task (i.e. serializing its internal configuration dictionary).
The idea is that later you could clone the HPO Task, edit the HPO configuration and launch the HPO on the trains-agent services queue. Basically allowing you to automate the automation, i.e. the HPO process.

The bug is that the HPO object assumes the internal representation dictionary is json serializable, unfortunately the Optuna parameter you are passing is an object (not a basic type).

I think the solution here is not to serialize the optimizer specific object (e.g. `optuna_sampler`), this should solve the issue and still allow you to configure the HPO from the UI.
What do you think?

**Comment by mhashas** [comment]
Hi,

Sounds good. For us, I don't think it's so important to automate the automation so I will use the work around till the fix is done. Thanks for the quick response (again).

Not sure if I should close the ticket or not, if you are tracking the issue feel free to close it.

**Comment by bmartinn** [comment]
Hi @mhashas 
RC is out with a fix, feel free to test it.
```
pip install trains==0.16.4rc0
```
