### ISSUE TITLE
How to pass non-default argparse values as parameters?

### ISSUE THREAD

**Issue by kirillfish** [allegroai/trains#262]
As can be found in docs and examples, `trains` takes arguments from `parser` during task initialization, and also can connect arguments from dicts and files with `task.connect` method. But as far as I can see, hyperparameters from `Configuration` section in web UI serve only for visualization and tracking purposes: changing parameters there doesn't affect values that are passed during execution (it's "one-way street"). I also cannot add arguments into `Script Path` field, as I would normally do when running it from console.

So, the questions are:

1. Are there any ways to pass any argparse values other than default ones, when launching experiments from web UI?
2. Are there any ways at all to change arguments and hyperparameters without modifying source code? Creating a separate Git branch with a new config for every experiment is not very convenient

**Comment by bmartinn** [comment]
Hi @kirillfish 

> But as far as I can see, hyperparameters from Configuration section in web UI serve only for visualization and tracking purposes

Actually, no :)
Let me unveil some of the mystery , when you execute your code in "manual mode" (i.e. from your pycharm/vscode/jupyter etc.)
`trains` logs everything into the UI, basically it takes the parameters from the code and logs them in the back-end.
When the `trains-agent` is executing the task (a.k.a "remote execution"), the opposite happens, and the parameters from the UI override the values in the code.
You can find more information on `trains-agent` in the [repository](https://github.com/allegroai/trains-agent).
Once you have agents running, you can start experimenting with [hyper-parameter optimization](https://github.com/allegroai/trains/blob/master/examples/optimization/hyper-parameter-optimization/hyper_parameter_optimizer.py) and [pipelines](https://github.com/allegroai/trains/blob/master/examples/pipeline/pipeline_controller.py) and other automations.

What do you think ?

**Comment by kirillfish** [comment]
I'm a bit confused now. I put an experiment into a queue which executes it on a remote agent, using a docker image that I specified. Is it what you call remote execution mode? 

In the UI, in Configuration > Hyperparameters > General tab, I can see all the arguments fetched from argparse and configs. So far, so good. Then, regardless of what I change in these parameters through web UI, my code still uses the values defined in the configs and argparse. The values from web UI are either rewritten again or they are never passed in the first place. Are these values passed to the code, and if yes, how do I find the exact place in code where they are updated?

**Comment by bmartinn** [comment]
Hi @kirillfish 

>I put an experiment into a queue which executes it on a remote agent, using a docker image that I specified. Is it what you call remote execution mode?

Correct :)

> Configuration > Hyperparameters > General tab, I can see all the arguments fetched from argparse

Wait, why? Argparse arguments should be under "Configuration > Hyperparameters -> Args" ?
If you are using `task.connect(...)` notice that in "remote execution" the object that will be changing is the object passed to the function call, now if that object is temporary, it will have no effect. 
For example (a bad example, so do not use it : )
``` python
default_value = 42
task.connect({'param_that_we_cannot_change': default_value})
```
What happens in remote execution is the `connect` function is changing the value of the temporary dict we created, **not** the variable inside the dict! (The actual limit on these kind of things, python does not allow for basic value passing by reference, so we cannot change them).

To the problem at hand:
Why isn't the argparse caught automatically by `trains` ? Could it be that `trains` is imported only after the parser parsed the argv? Notice importing `trains` has to happen before the actual parsing happens, `Task.init` can be called later, but the import cannot.

What do you think?

**Comment by kirillfish** [comment]
Hi @bmartinn, sorry for the late reply

> Wait, why? Argparse arguments should be under "Configuration > Hyperparameters -> Args" ?
No, they are always under `General` tab. Btw, there are also `User properties > Properties` and `Configuration objects > General` tabs, and I wasn't able to figure out their meaning. Could you please explain what they are for exactly, and how to modify them from the code? This is not as important as finding out the answers for the initial two questions though

`trains` is imported in the imports section, before the parsing happens of course. Argparse **is** caught by `trains`, but only the default values. The problem at hand (one of) is how to pass any values rather than the default ones, when running experiments through web UI.

I only pass dicts that were already defined into `task.connect`, so they are not temporary objects.

**Comment by kirillfish** [comment]
The second question was how to change hyperparameters in web UI before running the experiment

**Comment by bmartinn** [comment]
Hi @kirillfish 
> No, they are always under General tab

With v0.16  we introduced sections and names, I'm assuming you have previous `trains-server`/`trains` version and this is why it is under General (I would recommend to upgrade both the `trains-server` and `trains` to the latest versions)

I'll start with the last question, and then go back from there:
> how to change hyperparameters in web UI before running the experiment

Once you executed an experiment it becomes completed (or aborted) and frozen (i.e. non-editable).
You can "Reset" an experiment (right click -> "reset"), which clears the results and makes all the fields editable (and changes the experiment status to "draft")
You can "publish" an experiment (right click -> "publish"), locking this experiment and making sure no one will be able to reset/change it.
You can "clone" an experiment (right click -> "clone"), which creates a new editable copy of the experiment (status "draft")

"Draft" experiments are fully editable in the UI. Once you are done editing, enqueue them for execution.


Trains has three different types of Configurations:

- User Properties: key/value pairs that are always editable, allowing you to add information on experiments even post execution, for example `backbone_type=ResNet18` . You can later add them to the experiments' table view  by clicking the cogwheel on the right corner of the table, and adding custom columns ("+hyper-parameters").
- Hyper Parameters: Different section names, separate different types of hyper-parameters, for example argparse under "Args", dictionaries by default under "General", etc. A user can add multiple sections of hyperparameters from anywhere in the code by calling `Task.current_task().connect(my_dict, 'section_name')` . Like "User Properties" you can add these parameters as custom columns to the experiments' table.
- Configuration Objects: These are either configuration files or a dictionary representing a complex nested configuration object.
In both cases, you to edit the configuration file (or dict) as text , then get the text as a file/object in code, see details [here](https://allegro.ai/docs/task.html#trains.task.Task.connect_configuration)

Let me know if I missed anything :)

**Comment by kirillfish** [comment]
@bmartinn thank you for the detailed answer, but you didn't answer the questions...

**1. Passing any argparse values rather than default ones.**

To put it in another way, suppose I run some random experiment locally with no `trains` involved, specifying some parameters, say
```
python3 train.py --learning-rate 0.0003 --batch-size 32 --optimizer adamw
```
This would use non-default argument values in argparse. The question was: is it possible to use non-default argparse values when running the script in remote execution mode through web UI?

**2. Changing hyperparameters through web UI.** 

I know how to change them in the UI, but the problem is that they are *not passed* into code during execution. Values that are actually used are always the values that were read with `task.connect` and `task.connect_configuration` methods. So the question was: is it possible to change values in the web UI so that these values were actually used by the code?

**Comment by kirillfish** [comment]
I partially figured out an answer for the second question:

`task.connect()` does rewrite locally defined parameters with the ones defined through web UI, but this is applied only to configs, but not to argparse values (if there are argparse arguments with the same name, they remain intact)

**Comment by bmartinn** [comment]
Hi @kirillfish 

1.  Passing any argparse values rather than default ones.
This example is considered "manual" execution, everything you pass to `argparse` will be logged in the UI.
> when running the script using trains, in remote execution mode through web UI?

Yes, but notice the actual execution of the script will be done by `trains-agent` not manually by you (a.k.a you cannot run `python3 train.py  ...` and expect to get the parameters from the UI)

I think the main gap here is the following, in order to have the UI control the arguments, you **must** use the `trains-agent` to run your code. That means you have to spin an agent `trains-agent daemon ...` and enqueue the experiment in the UI.
See details on `trains-agent` [here](https://github.com/allegroai/trains-agent)

If you want to execute the code manually, you can however do the following:
Clone the experiment in the UI, change the parameters, copy the experiment ID (press on the ID button next to the experiment name), then run:
``` bash
trains-agent execute --id <paste_experiment_id_here>
```
WDYT?

**Comment by kirillfish** [comment]
Hi @bmartinn, sorry for the delayed response. Yes, this is exactly what I was looking for, thank you. That's why I decided to get rid of `argparse` in my code altogether, in order not to mix things up when `argparse` values interfere with config values. 

I'll check out manual execution on the agent, but this is not very convenient option (it's much better to manage all queues, agents and experiments from web UI). So the most viable option right now is to clone experiments and change parameters from the web UI
