### ISSUE TITLE
run manual_reporting.py breaks

### ISSUE THREAD

**Issue by philipskokoh** [allegroai/trains#27]
`manual_reporting.py` breaks now. It seems it's due to python 2 and 3 compatibility. 
I run the code using python 3.7.

```
$ python manual_reporting.py 
TRAINS Task: created new task id=a359fbe1bf4d43c4b99a0ab282be3a3e
TRAINS results page: None/projects/df19a47fd49248f2b6c4a1cd0163166d/experiments/a359fbe1bf4d43c4b99a0ab282be3a3e/output/log
DEBUG:root:This is a debug message
INFO:root:This is an info message
WARNING:root:This is a warning message
ERROR:root:This is an error message
CRITICAL:root:This is a critical message
hello
Traceback (most recent call last):
  File "manual_reporting.py", line 46, in <module>
    logger.report_image_and_upload("test case", "image uint", iteration=1, matrix=m)
  File "/home/user/anaconda3/envs/trains_py37/lib/python3.7/site-packages/trains/logger.py", line 45, in fixed_names
    func(self, title, series, *args, **kwargs)
  File "/home/user/anaconda3/envs/trains_py37/lib/python3.7/site-packages/trains/logger.py", line 517, in report_image_and_upload
    upload_uri = self._default_upload_destination or self._task._get_default_report_storage_uri()
  File "/home/user/anaconda3/envs/trains_py37/lib/python3.7/site-packages/trains/backend_interface/task/task.py", line 675, in _get_default_report_storage_uri
    elif parsed.netloc.startswith('demoapp.'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
======> WARNING! UNCOMMITTED CHANGES IN REPOSITORY https://github.com/allegroai/trains.git <======
```

**Comment by bmartinn** [comment]
@philipskokoh I was not able to reproduce this bug (manual_reporting.py runs fine on our python 3.7 environment)
Please include environment configuration (OS, Anaconda version, Trains version etc.)

That said, in your log, I see that something very strange:
> TRAINS results page: None/projects/df19a47fd49248f2b6c4a1cd0163166d/experiments/a359fbe1bf4d43c4b99a0ab282be3a3e/output/log

Notice that the first token in the results page is: "None/"

Could you verify the trains configuration (~/trains.conf), there might be a problem with the host definition there.

**Comment by philipskokoh** [comment]
Hi @bmartinn , 
here is my environment info: 
OS: Ubuntu 16.04.6 LTS
TRAINS version:  0.10.2
conda version : 4.5.11
conda-build version : 3.4.1

I think I roughly find the root of the issue (possibly a bug), and it's related to the "None/" token you mentioned before.
We are running the API server on port 5909, and I think the problem comes because of this custom API port.

If we look at the function where the error occured in task.py, `app_host` gets the value from `self._get_app_server()`. 
https://github.com/allegroai/trains/blob/9880581554f3f8f4c91744ca9cf091e17a1e784c/trains/backend_interface/task/task.py#L670-L681

If we looked at `self._get_app_server()`, it seems that the function does not return any value if the port is not 8008. The port 8008 and 8080 seem to be hard coded in the function. I think this is why it breaks.
https://github.com/allegroai/trains/blob/9880581554f3f8f4c91744ca9cf091e17a1e784c/trains/backend_interface/task/task.py#L688-L697

**Comment by philipskokoh** [comment]
Based on this two functions, looks like that 8008, 8080, and 8081 are hard coded.

**Comment by bmartinn** [comment]
@philipskokoh you are correct, there are currently two optional deployments:
Either single IP ports: 8008/8080/8081
Or subdomain deployment: app.* / api.* / files.*

We could probably add the option to configure all three manually...

**Comment by philipskokoh** [comment]
Thanks for the clarification @bmartinn . 
Yes, web app is working because we don't change the ports for webapp and files servers. We're changing api server because port 8008 is no longer available in our environment.

For the subdomain deployment, it means that:
api server: api.<ip_address>:8080
app server: app.<ip_address>:8080
file server: files.<ip_address>:8080
correct?

**Comment by bmartinn** [comment]
Yes, the subdomain deployment is correct.
(As long as they all have the same port number it will work, or even if you do not specify, i.e. 80 for http and 443 for https)
 
That said the Webapp also connects with the API server in a similar manner, so if the Webapp can't find the API server on the same IP on port 8008 (or on subdomain api.), it will run but you will keep getting errors and you will not be able to see the projects or experiments.

**Comment by philipskokoh** [comment]
I saw two commits (https://github.com/allegroai/trains/commit/51cc50e2391144c66c647c0d0075a6055ddd8f39 and https://github.com/allegroai/trains/commit/50ce49a3dd87389d22d43cf24292fff888f6915c) to handle separate api/web/file server config.

It seems you have just added a feature to separate api/web/file server configuration. I am going to try the latest update first.

**Comment by bmartinn** [comment]
:) try the latest release  candidate
`$ pip install trains==0.10.3rc1`

**Comment by philipskokoh** [comment]
`trains==0.10.3rc1` works!! Thanks a lot @bmartinn.
