### ISSUE TITLE
loguru support

### ISSUE THREAD

**Issue by igolan89** [allegroai/trains#29]
Hi, 
I'm using loguru as a logging package, and it's the TRAINS log can't catch the logged messages unless the task is initialized before importing loguru. 
1) Is it possible to fix it?
2) loguru print the messages formatted with pretty colors, If you could support parsing it in the UI it would be fantastic! :)

**Comment by bmartinn** [comment]
Thanks @igolan89 I was not aware of this very cool logger.
1. Yes, this will be fixed. I will keep you posted once we have an RC with the fix.
2. I will check, it looks like a cool feature to have.

**Comment by bmartinn** [comment]
You can now test with this release candidate :)
`$ pip install trains==0.10.3rc2`

**Comment by igolan89** [comment]
Very cool! The log now shows when initializing the task after import of loguru
A backend with color support would make me truly grateful ;)

**Comment by bmartinn** [comment]
Hi @igolan89 ,
Trains v0.13.0 was just released, with backend support as well :)
`$ pip install trains==0.13.0`

**Comment by igolan89** [comment]
Love it! Thanks guys, you rock!
