### ISSUE TITLE
make Trains intranet and k8s friendly

### ISSUE THREAD

**Issue by soyvv** [allegroai/trains#30]
Hi there,
Great project and thank you so much for sharing it!
I'm trying to set up the Train services on our intranet-based (which blocks internet connection) K8S cluster and faces the following issues:

1. the Train docker container (for web) has hard-coded the backend server ports (8008 etc), which makes it hard for K8S to dynamically link the train web server and backend service; could you make the ports configurable externally?
2. There're some internet resource links in the webapp, which,  in our intranet environment, cannot be loaded. Would it be possible to pack all resources inside the docker images? Or provide an "offline" mode to inject pre-downloaded resources. 

Thanks and Best Regards. 

zhikai

**Comment by bmartinn** [comment]
See trains-server on Kubernetes [issue](https://github.com/allegroai/trains-server/issues/12)
Did you check these?
https://github.com/allegroai/trains-server-k8s
https://github.com/allegroai/trains-server-helm

**Comment by bmartinn** [comment]
Closing, feature implemented.

**Comment by eladrich** [comment]
Hi,
Really enjoying this project, amazing work!
Are you still planning to add `plotly.js` to the package so it can run "offline"?

I'm using the `trains-server` on-premise and everything works great except for plotly.

Best,
Elad

**Comment by bmartinn** [comment]
Hi @eladrich thank you so much for the feedback, really appreciate it!
I know it was on the to do list for the upcoming version (coming really soon ;)
But let me check and get back to you...

**Comment by bmartinn** [comment]
@eladrich good news :tada: plotly.js will be served by the trains-server in the upcoming release :)

**Comment by eladrich** [comment]
Awesome🤘, thanks!
