### ISSUE TITLE
Using matplotlib figure show() method instead of plt.show()

### ISSUE THREAD

**Issue by motikadosh** [allegroai/trains#32]
Hi,
I would like to upload plots to my experiment.
I am not using plt.show() as the sample demonstrates.
I am using figure object with fig.show(), is it possible to have this figure uploaded to the experiment?

Thanks

**Comment by bmartinn** [comment]
Thank you, @motikadosh , I think you are correct.
This seems like a bug.
Let me verify and get back to you.

**Comment by bmartinn** [comment]
Try this RC, it should fix the problem :)
`$ pip install trains==0.10.3rc3`

**Comment by motikadosh** [comment]
Thanks a lot!!
I will try it in a short time.

Moti

**Comment by bmartinn** [comment]
Closing, due to lack of activity.
