### ISSUE TITLE
conda support

### ISSUE THREAD

**Issue by galprz** [allegroai/trains#38]
Any chance that i can use anaconda to resolve trains dependency ?

**Comment by bmartinn** [comment]
@galprz do you mean let conda install the requirements for the trains package ?
or add trains to the conda environment.yml ?

* If you want to make sure conda installs the requirements, then before installing TRAINS, you need to manually install the requirements:

```
git clone https://github.com/allegroai/trains.git
cd trains
conda install --yes --file requirements.txt
```

* If you need to add TRAINS to the conda environment.yml, then add the following to the yaml file:
```
dependencies:
  - pip:
    - trains
```
Full details on combining pip/conda here:
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually

**Comment by galprz** [comment]
tnx
