### ISSUE TITLE
trains doesn't support keras model save 

### ISSUE THREAD

**Issue by algguarding** [allegroai/trains#39]
Hello

When I use keras' model.save() method, it doesn't detect it automatically and I have to do it manually.
Any chance you can support this?
Attached the code I tried it with and the data it needs (it's just a sample code, not my own).

Please help :) 

[keras_model.zip](https://github.com/allegroai/trains/files/3497172/keras_model.zip)

**Comment by bmartinn** [comment]
Sure, let me check it.
I'll update soon.

**Comment by bmartinn** [comment]
@algguarding the attached code seems to work, and register the output model.
Tested on Ubuntu 16.04 Python 3.5 trains v0.10.4
What's the exact environment to reproduce the problem?

**Comment by bmartinn** [comment]
@algguarding could it be related to this issue #41
