### ISSUE TITLE
Code throws exception but task status is not set to “failed”

### ISSUE THREAD

**Issue by danmalowany** [allegroai/trains#4]
**Issue description:** Code throws exception (not caught) and exists with error, but task status changes to “completed”, instead of “failed”.

**Expected behavior:** I expect the status to be changed to “failed”.

**Environment:** Windows 10, python==3.6.7, tensorflow==1.10.0

**Comment by bmartinn** [comment]
Thanks, the bug was verified on v0.9.1 
Fix is already pushed to the master branch, and is part of the next release.
Please feel free to verify the bugfix with the latest release candidate:
`pip install trains==0.9.2rc0`

**Comment by danmalowany** [comment]
Thanks for the fast fix !
It works fine with trains==0.9.2rc0
