### ISSUE TITLE
Unstable connection causes training to freeze

### ISSUE THREAD

**Issue by OfirKP** [allegroai/trains#43]
Hi,
I tried to use TRAINS (v0.10.7) in an environment with an unstable connection to the internet.
While getting a lot of 'retrying to connect' messages, my training steps are being delayed (or stop).

I tried to set the following configuration in `/trains/backend_api/config/default/api.conf`, to minimize the amount of those kind of messages:
```
http {
        max_req_size = 15728640  # request size limit (smaller than that configured in api server)

        retries {
            # retry values (int, 0 means fail on first retry)
            total: 0     # Total number of retries to allow. Takes precedence over other counts.
            connect: 0   # How many times to retry on connection-related errors (never reached server)
            read: 0      # How many times to retry on read errors (waiting for server)
            redirect: 0  # How many redirects to perform (HTTP response with a status code 301, 302, 303, 307 or 308)
            status: 0   # How many times to retry on bad status codes

            # backoff parameters
            # timeout between retries is min({backoff_max}, {backoff factor} * (2 ^ ({number of total retries} - 1))
            backoff_factor: 1000.0
            backoff_max: 1.0
        }

        wait_on_maintenance_forever: false

        pool_maxsize: 512
        pool_connections: 512
    }
```

After cutting off the internet connection in the middle of a training, it froze completely with an infinitely repeating message: `Failed logging task to backend (1 lines)`.

Is there a workaround for working offline (in which TRAINS will completely stop reporting), or at least one that won't interfere with the training steps (without freeze or delay)?

**Comment by bmartinn** [comment]
Hi @OfirKP , the trains package was designed with always on network connection in mind, unfortunately there is no 'offline' option at the moment.

That said let me expand on the network issues you seem to run into:

If a connection is dropped (such as in your case), it will retry to connect to the server, these are the retry messages you keep getting. 

If a connection was dropped after a socket was created (post handshake) it will use the socket request timeout (imagine a very very very slow download connection, this is essentially the same timeout).  This timeout is defined to 10 minutes, after 10min passed and the request didn't return fully, a new connection will be established. 

Setting retry limit to zero will not effect the socket timeout, and I suspect that this is was you observed, when you completely cut the network connections.

My quickest solution for you is to mark out the `Task.init()` line, whenever you are in unstable network environment (such as, commuting on a train :smiley:  ).

**Comment by bmartinn** [comment]
Closing, due to lack of activity.
