### ISSUE TITLE
'Compare Experiments' feature doesn't display scalar charts 

### ISSUE THREAD

**Issue by OfirKP** [allegroai/trains#44]
I'm having issues with the 'Compare Experiments' feature (TRAINS v0.10.7).

After selecting multiple experiments, clicking on 'Compare' and navigating to the 'Scalar Charts' tab, I get this blank content page:
 
![image](https://user-images.githubusercontent.com/11351634/65515713-5fa5ef80-dee8-11e9-966b-9bb854deaee0.png)

This bug is not consistent, as sometimes the charts would render correctly and sometimes they won't.
I tried refreshing the page and logging out and in to the panel multiple times, while comparing the same experiments, but the charts wouldn't load (it also occurs with other finished experiments).

**Comment by JDennisJ** [comment]
Hi @OfirKP ,

Can you please share which trains-server do you use?

**Comment by OfirKP** [comment]
Hi, it's a local trains-server with v0.10.1.

**Comment by bmartinn** [comment]
First of all, good news, we just release trains-server v0.11.0 :tada: 
Let me know if the problem consists. 
If it does, please send the browser console log, there might be some warning/error messages waiting for us there.

**Comment by bmartinn** [comment]
Closing, due to lack of activity.
