### ISSUE TITLE
expanding artifact uniqueness comparison criteria

### ISSUE THREAD

**Issue by algguarding** [allegroai/trains#45]
Hello,

In your current implementation of artifact feature, you are checking to see if the entire dataframe row is the same, and if even one column is different you'll mark these 2 rows as unique.

On my testing code, I am going over a CSV file that gives me annotations of videos, I sometime make a mistake and have 2 rows with the same video but with different annotation, it is very hard to avoid as this mistake.

I want to have a feature where comparing 2 rows can be done based on a single or multiple columns, IE, if first column called "name" is the same, but the rest are not (what I use for annotations) you'll indicate that these 2 rows are the same.
I want to be able to choose which columns to compare, or to just have the configuration as it is now (compare all columns).
It will be good to have this flexibility.

Thank you

**Comment by bmartinn** [comment]
Thanks for the suggestion @algguarding ,
Making sure I understand you correctly, you suggest to add a parameter to Task.register_artifact, 
where you could select specific columns for the "uniqueness" and "overlap between artifacts" calculation?

**Comment by algguarding** [comment]
Yes this was my meaning.
I think that by default, you can compare every column, and have a parameter that chooses which columns you're comparing.
If in 2 rows the columns it's comparing are the same, then we conclude these 2 rows are identical, regardless of other columns which can be different or the same, they are ignored in the comparison.

I want to be able to specify which columns will be compared.

**Comment by bmartinn** [comment]
Cool feature
I'll update here once it is added, shouldn't take too long ;)

**Comment by bmartinn** [comment]
Hi @algguarding  ,
Trains v0.13.0 was just released, with artifact uniqueness support.
`$ pip install trains==0.13.0`
