### ISSUE TITLE
_FileStorageDriver.download_object does not contain callback argument

### ISSUE THREAD

**Issue by xandox** [allegroai/trains#48]
Steps for reproduce:
1. init task with `task = Task.init(project_name='example', task_name='example', output_uri='local_folder')`
2. setup InputModel with 
```
input_model = InputModel.import_model('file://local_folder/...') # uri from model page MODEL URI field
input_model.connect(task)
```
3. try to load state dict to your pytorch model
```
model.load_state_dict(torch.load(input_model.get_weights()))
```

logs will contain:
```
2019-10-14 16:11:07,399 - trains.model - INFO - Selected model id: 6b56ee9709314f35b0a804914a7063d5
2019-10-14 16:11:07,595 - trains.model - INFO - Selected model id: 58791155e4e444ae97d5721fcc22b2bc
2019-10-14 16:11:07,643 - trains.Task - WARNING - Task connect, second input model is not supported, adding into comment section
2019-10-14 16:11:09,728 - trains.model - INFO - Selected model id: 622297cf18a74496b406479907bc1908
2019-10-14 16:11:09,854 - trains.storage - INFO - Start downloading from file:///ds2/trained_modeles/examples/pytorch with
tensorboard.6190111e06b943c597febc9287e95b12/models/model15 2019-10-14 16:11:09,854 - trains.storage - ERROR - Could not download
file:///ds2/trained_modeles/examples/pytorch with tensorboard.6190111e06b943c597febc9287e95b12/models/model15 , err: download_object() got an unexpected keyword argument 'callback'
```

Environment:
`trains.__version__ = '0.11.2'`

**Comment by xandox** [comment]
And I have a question about log :)
What is WARNING about? And what I have to do for get rid of it?

**Comment by bmartinn** [comment]
Thank you @xandox , 
1. Bug is confirmed, I'll update here once we have an RC with a patch, should not take long.
2. Regrading the Warning, currently the system will only link to a single input/output model per experiment. 
The output models still contain link to the creator experiment, but not the other way around.
The warning is to let you know that you are using two input models (id: 6b56ee9709314f35b0a804914a7063d5 and id: 58791155e4e444ae97d5721fcc22b2bc) but the UI will only show the first one and put the links to the others in the description section of the experiment.
I'm hoping we get to fix that soon and remove the warning :)

**Comment by bmartinn** [comment]
Hi @xandox , RC with a fix is now available
It should solve the issue  :smiley:  

`pip install trains==0.11.3rc0`

**Comment by xandox** [comment]
Grate! Thank you very match.

Have I close this issue or you close it by you self when final release will be released?

**Comment by bmartinn** [comment]
Thanks @xandox, v0.11.3 was officially released, I'm closing the issue.
