### ISSUE TITLE
If I “stop” the experiment in the web-app, process continues to run

### ISSUE THREAD

**Issue by danmalowany** [allegroai/trains#5]
**Issue description**: Code running on Windows 10 64-bit machine, if I “stop” the experiment in the web-app (right click -> “stop”), process continues to run (as if the “stop” command never happened).

**Expected behaviour**: I expected the experiment to terminate.

**Environment**: Windows 10, python==3.6.7, tensorflow==1.10.0, trains==0.9.0

**Comment by bmartinn** [comment]
Yes this behavior is a bug, it is verified on v0.9.1
The fix is already pushed to the master branch, and is part of the next release.
You can already get the bug fix with the latest release candidate:

`pip install trains==0.9.2rc0`

Le me know if  the problem consists

**Comment by danmalowany** [comment]
Just finished trying out trains==0.9.2rc0 and it works fine.
Thanks for the fast fix !
