### ISSUE TITLE
Parallel Coordinates Plot

### ISSUE THREAD

**Issue by majdzr** [allegroai/trains#53]
Feature request: To be able to create a parallel coordinates plot in TRAINS in order to compare several hyper-parameters in respect to a specific metric, a similar feature is available in Tensorboard and MLFlow.

**Comment by bmartinn** [comment]
@majdzr thank you for the suggestion, I think it is a great idea.
Meanwhile, there is probably a way to achieve the same exploration with python code + plotly.
Let me see what I can come up with :)

**Comment by bmartinn** [comment]
Hi @majdzr ,
Trains-Server v0.13.0 was just released, with parallel coordinates plot available in the experiments comparison view under the Hyper Parameters section :)

**Comment by majdzr** [comment]
I saw the announcement last week. Amazing! Thank you.

**Comment by majdzr** [comment]
Hey,

Very nice and useful feature. Thanks again for adding it. 
One remark, can you please enable highlighting the plot once the mouse is over it? Maybe also highlighting the experiment name in the legend and the values of the parameters involved in the comparison? 
Thanks!
