### ISSUE TITLE
Deprecation warnings whilst using trains

### ISSUE THREAD

**Issue by SeanNaren** [allegroai/trains#56]
Hey guys! During training, when trains is enabled I keep getting spammed with these messages in stdout. Any ideas what could be causing this? I'll be investigating further to see what the issue is but any help would be appreciated.

```
/local/sean.narenthiran/anaconda3/lib/python3.7/site-packages/jsonschema/validators.py:896: DeprecationWarning:

The types argument is deprecated. Provide a type_checker to jsonschema.validators.extend instead.
```

**Comment by bmartinn** [comment]
Hi @SeanNaren , What's the `trains` & `trains-server` versions you are using? Also what's the `jsonschema` package version you have installed?

**Comment by SeanNaren** [comment]
Thanks for the quick response! `trains==0.12.0`  `jsonschema==3.0.2`. For the train server we use docker-compose so that pulls `latest` for the trains-server!

**Comment by bmartinn** [comment]
I can't seem to reproduce this warning...
I assume `jsonschema` package changed the interface between v2 and v3, but I can't find where the mismatch is.
Could you please post a short code snippet, reproducing the warning?

**Comment by bmartinn** [comment]
Hi @SeanNaren, 

I think we located the mismatch, as I suspected, starting `jsonschema` v3, a parameter was deprecated in the `jsonschema` package. 

We will fix it soon, but until we release a new `trains` package, you can down grade `jsonschema` to 2.6 or just ignore the warning :)

And again, thank you for noticing!

I'll post here once an update is in RC

**Comment by SeanNaren** [comment]
@bmartinn Thanks so much! Would love to ignore the warnings but the spam is unreal... Cheers for all your help!

**Comment by bmartinn** [comment]
Hi @SeanNaren your timing was perfect, last commit to 0.12.1 release :smile: 

`$ pip install trains==0.12.1`

Let me know if the issue was solved

**Comment by SeanNaren** [comment]
Thanks man! Verified it fixed on my end!
