### ISSUE TITLE
Set BASE DOCKER IMAGE from env

### ISSUE THREAD

**Issue by shaulimaya** [allegroai/trains#58]
Hey!
I would like to be able to set the base docker image by special env , i.e. TRAINS_BASE_DOCKER_IMAGE

Thanks :)

**Comment by bmartinn** [comment]
Great idea! it will be part of the next trains release, probably something like:
TRAINS_DOCKER_IMAGE

I'll update here once we have an RC with support for this feature.

**Comment by bmartinn** [comment]
Hi @shaulimaya ,
Trains v0.13.0 was just released, with `TRAINS_DOCKER_IMAGE` env var support :)
`$ pip install trains==0.13.0`
