### ISSUE TITLE
pip install trains, fails on Amazon Linux AMI

### ISSUE THREAD

**Issue by yaelsilb** [allegroai/trains#6]
Got he following error when trying to install trains on Amazon Linux AMI:
$ pip install trains --user
Collecting trains
  Using cached https://files.pythonhosted.org/packages/9c/f0/2c3e1e8a765fb1a8f2714530bce27c11d35a6d640928dd7608466ef3427a/trains-0.9.2-py2.py3-none-any.whl
Collecting enum34>=0.9 (from trains)
  Downloading https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Collecting apache-libcloud>=2.2.1 (from trains)
  Downloading https://files.pythonhosted.org/packages/07/c3/ddbd6b48395d0825f9910e5724a098e9de1e720d4e7124625a8aff1eedec/apache_libcloud-2.5.0-py2.py3-none-any.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 13.2MB/s 
Collecting plotly>=3.9.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/ff/75/3982bac5076d0ce6d23103c03840fcaec90c533409f9d82c19f54512a38a/plotly-3.10.0-py2.py3-none-any.whl (41.5MB)
    100% |████████████████████████████████| 41.5MB 1.2MB/s 
Collecting funcsigs>=1.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: boto3>=1.9 in /home/ec2-user/.local/lib/python3.6/site-packages (from trains) (1.9.123)
Requirement already satisfied: botocore>=1.12 in /home/ec2-user/.local/lib/python3.6/site-packages (from trains) (1.12.123)
Collecting pyhocon>=0.3.38 (from trains)
  Downloading https://files.pythonhosted.org/packages/3f/35/34e16968df0b8b65d3696d80b8add0aaffd4f0461c1ef3c0f066fdc747e8/pyhocon-0.3.51.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 27.2MB/s 
Requirement already satisfied: python-dateutil>=2.6.1 in /home/ec2-user/.local/lib/python3.6/site-packages (from trains) (2.8.0)
Collecting attrs>=18.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting opencv-python>=3.2.0.8 (from trains)
  Downloading https://files.pythonhosted.org/packages/7b/d2/a2dbf83d4553ca6b3701d91d75e42fe50aea97acdc00652dca515749fb5d/opencv_python-4.1.0.25-cp36-cp36m-manylinux1_x86_64.whl (26.6MB)
    100% |████████████████████████████████| 26.6MB 1.9MB/s 
Collecting pyjwt>=1.6.4 (from trains)
  Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting future>=0.16.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 29.0MB/s 
Collecting google-cloud-storage>=1.13.2 (from trains)
  Using cached https://files.pythonhosted.org/packages/e2/4e/aee59b19321eb1063317c2e6fa4c2f3cfe21740586de78578eedbd2bed3d/google_cloud_storage-1.16.1-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.10 in /home/ec2-user/.local/lib/python3.6/site-packages (from trains) (1.16.2)
Collecting humanfriendly>=2.1 (from trains)
  Downloading https://files.pythonhosted.org/packages/90/df/88bff450f333114680698dc4aac7506ff7cab164b794461906de31998665/humanfriendly-4.18-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 29.0MB/s 
Collecting typing>=3.6.4 (from trains)
  Downloading https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting coloredlogs>=10.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/08/0f/7877fc42fff0b9d70b6442df62d53b3868d3a6ad1b876bdb54335b30ff23/coloredlogs-10.0-py2.py3-none-any.whl (47kB)
    100% |████████████████████████████████| 51kB 23.9MB/s 
Collecting jsonschema>=2.6.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/aa/69/df679dfbdd051568b53c38ec8152a3ab6bc533434fc7ed11ab034bf5e82f/jsonschema-3.0.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 26.1MB/s 
Requirement already satisfied: urllib3>=1.22 in /home/ec2-user/.local/lib/python3.6/site-packages (from trains) (1.24.1)
Collecting psutil>=3.4.2 (from trains)
  Downloading https://files.pythonhosted.org/packages/1c/ca/5b8c1fe032a458c2c4bcbe509d1401dca9dda35c7fc46b36bb81c2834740/psutil-5.6.3.tar.gz (435kB)
    100% |████████████████████████████████| 440kB 28.5MB/s 
Collecting requests-file>=1.4.2 (from trains)
  Downloading https://files.pythonhosted.org/packages/23/9c/6e63c23c39e53d3df41c77a3d05a49a42c4e1383a6d2a5e3233161b89dbf/requests_file-1.4.3-py2.py3-none-any.whl
Collecting furl>=2.0.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/bd/b6/302ecc007de38274509d6397300afd2e274aba7f1c3c0a165b5f1e1a836a/furl-2.0.0-py2.py3-none-any.whl
Collecting pathlib2>=2.3.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Requirement already satisfied: six>=1.11.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from trains) (1.12.0)
Collecting PyYAML>=3.12 (from trains)
  Using cached https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz
Collecting colorama>=0.4.1 (from trains)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting tqdm>=4.19.5 (from trains)
  Using cached https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.18.4 in /home/ec2-user/.local/lib/python3.6/site-packages (from trains) (2.21.0)
Collecting jsonmodels>=2.2 (from trains)
  Downloading https://files.pythonhosted.org/packages/e9/c4/93ce38601474210eeb97b50c7f65d48827ee19f5e7b6e51b63b3684059df/jsonmodels-2.4-py2.py3-none-any.whl
Collecting watchdog>=0.8.0 (from trains)
  Downloading https://files.pythonhosted.org/packages/bb/e3/5a55d48a29300160779f0a0d2776d17c1b762a2039b36de528b093b87d5b/watchdog-0.9.0.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 29.3MB/s 
Requirement already satisfied: pytz in /home/ec2-user/.local/lib/python3.6/site-packages (from plotly>=3.9.0->trains) (2018.9)
Collecting decorator>=4.0.6 (from plotly>=3.9.0->trains)
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting retrying>=1.3.3 (from plotly>=3.9.0->trains)
  Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
Collecting nbformat>=4.2 (from plotly>=3.9.0->trains)
  Downloading https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl (155kB)
    100% |████████████████████████████████| 163kB 34.4MB/s 
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/.local/lib/python3.6/site-packages (from boto3>=1.9->trains) (0.9.4)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in /home/ec2-user/.local/lib/python3.6/site-packages (from boto3>=1.9->trains) (0.2.0)
Requirement already satisfied: docutils>=0.10 in /home/ec2-user/.local/lib/python3.6/site-packages (from botocore>=1.12->trains) (0.14)
Requirement already satisfied: pyparsing>=2.0.3 in /home/ec2-user/.local/lib/python3.6/site-packages (from pyhocon>=0.3.38->trains) (2.2.0)
Collecting google-auth>=1.2.0 (from google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 31.3MB/s 
Collecting google-cloud-core<2.0dev,>=1.0.0 (from google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/98/7f/ff56aec313787577e262d5a2e306c04aef61c5c274699ff9fb40095e6691/google_cloud_core-1.0.2-py2.py3-none-any.whl
Collecting google-resumable-media>=0.3.1 (from google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/e2/5d/4bc5c28c252a62efe69ed1a1561da92bd5af8eca0cdcdf8e60354fae9b29/google_resumable_media-0.3.2-py2.py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema>=2.6.0->trains)
  Downloading https://files.pythonhosted.org/packages/68/0b/f514e76b4e074386b60cfc6c8c2d75ca615b81e415417ccf3fac80ae0bf6/pyrsistent-0.15.2.tar.gz (106kB)
    100% |████████████████████████████████| 112kB 34.8MB/s 
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from jsonschema>=2.6.0->trains) (28.8.0)
Collecting orderedmultidict>=1.0 (from furl>=2.0.0->trains)
  Downloading https://files.pythonhosted.org/packages/05/70/9f0a8867d4d98becf60dc5707e10b39930747ee914dae46414b69e33a266/orderedmultidict-1.0-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests>=2.18.4->trains) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests>=2.18.4->trains) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in /home/ec2-user/.local/lib/python3.6/site-packages (from requests>=2.18.4->trains) (2.8)
Collecting argh>=0.24.1 (from watchdog>=0.8.0->trains)
  Downloading https://files.pythonhosted.org/packages/06/1c/e667a7126f0b84aaa1c56844337bf0ac12445d1beb9c8a6199a7314944bf/argh-0.26.2-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog>=0.8.0->trains)
  Downloading https://files.pythonhosted.org/packages/e7/7f/470d6fcdf23f9f3518f6b0b76be9df16dcc8630ad409947f8be2eb0ed13a/pathtools-0.1.2.tar.gz
Collecting traitlets>=4.1 (from nbformat>=4.2->plotly>=3.9.0->trains)
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 29.6MB/s 
Collecting ipython-genutils (from nbformat>=4.2->plotly>=3.9.0->trains)
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting jupyter-core (from nbformat>=4.2->plotly>=3.9.0->trains)
  Downloading https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 36.4MB/s 
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.2.0->google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/91/f0/b03e00ce9fddf4827c42df1c3ce10c74eadebfb706231e8d6d1c356a4062/pyasn1_modules-0.2.5-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 29.4MB/s 
Collecting rsa>=3.1.4 (from google-auth>=1.2.0->google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.2.0->google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
Collecting google-api-core<2.0.0dev,>=1.11.0 (from google-cloud-core<2.0dev,>=1.0.0->google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/10/d6/8b1e8d79a8a56649af3a094e3d90dd213278da942f36d831b57c0ca4a503/google_api_core-1.11.1-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 30.0MB/s 
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth>=1.2.0->google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 31.9MB/s 
Collecting googleapis-common-protos!=1.5.4,<2.0dev,>=1.5.3 (from google-api-core<2.0.0dev,>=1.11.0->google-cloud-core<2.0dev,>=1.0.0->google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/eb/ee/e59e74ecac678a14d6abefb9054f0bbcb318a6452a30df3776f133886d7d/googleapis-common-protos-1.6.0.tar.gz
Collecting protobuf>=3.4.0 (from google-api-core<2.0.0dev,>=1.11.0->google-cloud-core<2.0dev,>=1.0.0->google-cloud-storage>=1.13.2->trains)
  Downloading https://files.pythonhosted.org/packages/d2/fb/29de8d08967f0cce1bb10b39846d836b0f3bf6776ddc36aed7c73498ca7e/protobuf-3.8.0-cp36-cp36m-manylinux1_x86_64.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 23.3MB/s 
google-api-core 1.11.1 has requirement setuptools>=34.0.0, but you'll have setuptools 28.8.0 which is incompatible.
Installing collected packages: enum34, apache-libcloud, decorator, retrying, pyrsistent, attrs, jsonschema, ipython-genutils, traitlets, jupyter-core, nbformat, plotly, funcsigs, pyhocon, opencv-python, pyjwt, future, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, google-resumable-media, google-cloud-storage, humanfriendly, typing, coloredlogs, psutil, requests-file, orderedmultidict, furl, pathlib2, PyYAML, colorama, tqdm, jsonmodels, argh, pathtools, watchdog, trains
  Running setup.py install for retrying ... done
  Running setup.py install for pyrsistent ... done
  Running setup.py install for pyhocon ... done
  Running setup.py install for future ... done
  Running setup.py install for googleapis-common-protos ... error
    Complete output from command /usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-uvetk06x/googleapis-common-protos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ji5tpf0g/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "/usr/local/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
        @_call_aside
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-uvetk06x/googleapis-common-protos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ji5tpf0g/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-uvetk06x/googleapis-common-protos/

**Comment by bmartinn** [comment]
Seems like an issue with the google-api-core package and setuptools compatibility

> google-api-core 1.11.1 has requirement setuptools>=34.0.0, but you'll have setuptools 28.8.0 which is incompatible.

Try updating setuptools

`pip install -U setuptools --user`

Let me know if it fixed the problem

**Comment by yaelsilb** [comment]
Great, I added it to the requirement file.
Thanks!
