### ISSUE TITLE
SVN support

### ISSUE THREAD

**Issue by fcakyon** [allegroai/trains#61]
This is a feature request.

Currently trains server supports git as a version control platform; in other words, when the script of interest is connected to trains server in a git folder, trains-agent creates an environment cloning this git repository.

Do you have any plans for adding Subverison (SVN) support, in addition to git?

**Comment by bmartinn** [comment]
Hi @fcakyon ,

For the time being we have support for git, as this is probably the most commonly used version control.

We previously had support for mercurial, but due to lack of interest we kind of dropped it.

If enough users vote here +1 we will add it.

That said, feel free to add a PR with this ability :)
If you wish I could point to where/how one could easily add any VCS support :smile:

**Comment by fcakyon** [comment]
Thanks for the response @bmartinn , would be great if you could show where&how to add it  :)

**Comment by bmartinn** [comment]
You can find the git auto detection support code [here](https://github.com/allegroai/trains/blob/master/trains/backend_interface/task/repo/detectors.py#L187)

Which you can basically copy paste with slight modifications (see below),
and change the execution commands on `_get_commands` to return the needed values.

For example:
`url` : should return the repository url link
`branch` : should return the repository branch name
`root` : is the root path of the repository (i.e. the absolute path to where the .git folder is)
etc.

Template code below:
```python
class SvnDetector(Detector):
    def __init__(self):
        super(SvnDetector(, self).__init__("svn")

    def _get_commands(self):
        return self.Commands(
            url=["git", "ls-remote", "--get-url", "origin"],
            branch=["git", "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}"],
            commit=["git", "rev-parse", "HEAD"],
            root=["git", "rev-parse", "--show-toplevel"],
            status=["git", "status", "-s"],
            diff=["git", "diff"],
            modified=["git", "ls-files", "-m"],
            branch_fallback=["git", "rev-parse", "--abbrev-ref", "HEAD"],
        )
```

BTW: from looking at the SVN [documentation](https://subversion.apache.org/quick-start) it looks like it should not be very hard to match to the git commands :)
