### ISSUE TITLE
How to stop tracking stdout

### ISSUE THREAD

**Issue by zomux** [allegroai/trains#65]
During training, I show some information using codes like

```
sys.stdout.write("debug info \r")
```

How can I get rid of them in the log?

**Comment by JDennisJ** [comment]
Hi @zomux ,

You can remove the logs output by removing the sys.stdout from the logger, just add those lines:
```
from trains.logger import StdStreamPatch

StdStreamPatch.remove_std_logger()
```

and logs output won't be sent.

**Comment by zomux** [comment]
Thank you.
