### ISSUE TITLE
auto-scroll

### ISSUE THREAD

**Issue by majdzr** [allegroai/trains#66]
In a failed experiment, when looking at the Results/Log tab, the tab auto scrolls to the end of the log file every couple of seconds.

**Comment by JDennisJ** [comment]
Hi @majdzr ,

On the upper right corner, you have `Auto Refresh` button (by default it's on), your screen will be updated and the layout of the log too according to this toggle.

You can disable it and by removing the 'V' mark, and after it, the log layout should be static.

Can this be this issue?

**Comment by majdzr** [comment]
Hi @JDennisJ 
Thanks for the quick response. 
Indeed, the issue disappears once I disable the auto refresh.
I still think it's an issue, specially that the experiment is already stopped and there is nothing to refresh (unlike other running tabs), but your suggestion just solved it. Thanks. I can close the issue if you prefer.

**Comment by JDennisJ** [comment]
Hi @majdzr 

You are right, the auto-refresh toggle should be disabled. We will fix it in future versions.
Until this will be fixed, please use the workaround as a temporary solution.

I'll update here once the bug is fixed.

**Comment by JDennisJ** [comment]
Hi @majdzr ,

This issue is now fixed in the new release of Trains-Server v0.13.0 :fireworks:
