### ISSUE TITLE
Trains cannot track special argument values

### ISSUE THREAD

**Issue by eyalziv** [allegroai/trains#69]
When an argument is of dictionary type as follow:  {'a > 5': 0.4}, 
Trains raises an exception and stops documenting the following arguments in 'hyperparameters' tab

**Comment by bmartinn** [comment]
Bug verified, the *trains-server*  does not allow white-space in the hyper-parameters.
It will be fixed in the next *trains-server* release. 

Until then, a workaround would be removing the spaces:
```
 {'a>5': 0.4},
```

**Comment by eyalziv** [comment]
Hey Martin,
Thank you for your fast response!

The example I gave you wasn’t quite similar to my use case. Actually, I have a dictionary argument which contains both whitespaces and ‘.’ Character.
This argument looks like:

{‘a > 0.5’: ‘0.4’} 

Will you have a fix for that constraint (of special characters ‘.’) as well in the next release?

Best regards,
Eyal

**Comment by bmartinn** [comment]
Yes @eyalziv, currently  " ", "." and "$"  (space, dot, dollar_sign) are not supported in a hyper-parameter key. All three restrictions will be fixed in the next *trains-server* release :)

**Comment by bmartinn** [comment]
Hi @eyalziv ,
Trains and Trains-Server v0.13.0 were just released, with no restriction on hyper-parameter keys.
