### ISSUE TITLE
SSL Conection error [CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by amirkforesightauto** [allegroai/trains#7]
I have installed trains and when i run my code with the required 2 lines of integration, i get the following error message:
Retrying (Retry(total=239, connect=240, read=240, redirect=240, status=240)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)': /auth.login
It seems like the firewall at my company that monitors https connections blocks the connection to your demo server.
Is there a way to fix it?

**Comment by raviv** [comment]
@amirkforesightauto  You can run a trains server locally.
See here: https://github.com/allegroai/trains-server

**Comment by amirkforesightauto** [comment]
I'm currently trying the demo server.

**Comment by bmartinn** [comment]
Yes, it seems your company's firewall is doing some MITM.
Solutions:
1) Direct python "requests" to use the enterprise certificate file. This can be achieved by setting the OS environment variables CURL_CA_BUNDLE or REQUESTS_CA_BUNDLE . 

> You can see a detailed discussion here
> https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module


2) Latest release-candidate already contains a feature to disable certificate verification (for security reasons this is not encouraged) 
In order to use this new feature:
- Upgrade the trains package:
`pip install trains==0.9.3rc1`
- Create a new **trains.conf** configuration file (regular text file), containing:
`api {
     verify_certificate = False
}
`
- Copy the **trains.conf** file to ~/trains.conf (on windows: C:\Users\your_username\trains.conf)

Let me know if it solved the problem

**Comment by amirkforesightauto** [comment]
Thanks for the fast replies.
I did both solutions:
1. CURL_CA_BUNDLE="" python   <my python script>
I get the following error:
W0620 10:20:00.536018 123 connectionpool.py:665] Retrying (Retry(total=236, connect=240, read=236, redirect=240, status=240)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))': /auth.login
W0620 10:20:01.016951 123 connectionpool.py:851] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

2. uninstalled trans and then installed the specific version. I get the same error report as before.

**Comment by amirkforesightauto** [comment]
Thanks for the fast replies.
I did both solutions:

 1.   CURL_CA_BUNDLE="" python
    I get the following error:
    W0620 10:20:00.536018 123 connectionpool.py:665] Retrying (Retry(total=236, connect=240, read=236, redirect=240, status=240)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))': /auth.login
    W0620 10:20:01.016951 123 connectionpool.py:851] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning)

2.   uninstalled trans and then installed the specific version.
created 
~/trans.conf in 
with the code api { verify_certificate = False }
I get the a new error report:
W0620 10:59:45.468020 42 connectionpool.py:665] Retrying (Retry(total=237, connect=240, read=240, redirect=240, status=240)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)': /auth.login

**Comment by amirkforesightauto** [comment]
I tired the following lines:
TRAINS_API_HOST_VERIFY_CERT=False python
from trains import Task
task = Task.init(project_name, task_name)

and got the following messag:
InsecureRequestWarning: Certificate verification is disabled! Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Retrying (Retry(total=239, connect=240, read=239, redirect=240, status=240)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))': /auth.logine:

I then tried going in the following website in my browser  
https://demoapi.trainsai.io
and realized that this site is blocked by my company's firewall.

**Comment by bmartinn** [comment]
Great news & I'm happy to hear IT agreed to open the firewall :)
Meanwhile, the feature already made its way to the current release v0.9.3
You can now safely upgrade.
