### ISSUE TITLE
can't connect to trains server deployed on AWS with AMI

### ISSUE THREAD

**Issue by boazpe** [allegroai/trains#71]
Hello trains team,

I'm trying to install trains-server,
The steps i took:

1. deployed trains on AWS using the AMI (eu-west-1 : ami-04293fbba6d3acad1).

2. opened tcp ports 8080, 8081, 8008 .

3. on my client, I've typed trains-init and:
3.1 pasted the credentials i've created on [the profile page](https://demoapp.trains.allegro.ai/profile).
3.2 entered the public ip of the ec2 instance as api host (the default ports were added automatically). 

I than get " Verifying credentials ... " message where the process gets stuck in.

What am i doing wrong?

Thanks,
Boaz

**Comment by bmartinn** [comment]
Hi @boazpe ,
Just to clarify, in section 3.1 the link points to the demoapp server, not to your *trains-server* installation, is that on purpose?

First try to open the web browser and see if you can access the web UI of your *trains-server*.
It should look something like: `http://<public_aws_ip>:8080/`
If you have that working, you need to create your credentials by browsing to  `http://<public_aws_ip>:8080/profile`

Once that is working, re-run `trains-init`

p.s.
It looks like there is a bug in the `trains-init` configuration wizard, where errors are not printed.
I'll make sure this is solved for the next version.

**Comment by boazpe** [comment]
Thanks for the swift reply!

yeah , i misunderstood the instructions and created a credentials on the demo app instead of the deployed server.

However, i'm still stuck at the same stage (" Verifying credentials ... ")
I accessed the deployed trains server,  created the credentials, and re-ran the trains-init.

anyway i can get more info that will help finding out the cause?

Thanks,
Boaz

**Comment by bmartinn** [comment]
Which OS / trains / trains-server versions are you using?

Another test would be to configure it manually.

Could you copy the default trains.conf from [here](https://github.com/allegroai/trains/blob/master/docs/trains.conf) to `~/trains.conf` and edit the following fields:
```
api {
    web_server: "http://<aws_public_ip>:8080"
    api_server: "http://<aws_public_ip>8008"
    files_server: "http://<aws_public_ip>8081"

    # Credentials directly from the webapp, http://<aws_public_ip>:8080/profile
    credentials {"access_key": "AAA", "secret_key": "BBB"}
}
```

Once you have that, try to execute in python:
```python
from trains import Task
task = Task.init('examples', 'test connection')
```

**Comment by boazpe** [comment]
cool! that worked.

if you do want to investigate more about why it didn't work before for me:
yesterday my client was on windows, and today i'm using ubuntu. 
trains version: 0.12.2
trains server: I've deployed the ami-04293fbba6d3acad1

P.S
trains looks like an amazing tool and bravo on releasing it for free.

Thanks again,
Boaz
