### ISSUE TITLE
Can't apply smoothing in scalar charts when comparing experiments

### ISSUE THREAD

**Issue by eyalziv** [allegroai/trains#73]
For some reason, I cannot apply the smoothing filter to scalar charts when I'm in 'compare experiments' tab

![image](https://user-images.githubusercontent.com/59035635/71642276-6c896a80-2cb1-11ea-9339-b1e989aac6af.png)

**Comment by bmartinn** [comment]
Hi @eyalziv ,
This feels like the same issue #55 , What version of *trains-server* are you using?

**Comment by eyalziv** [comment]
Hey Martin,

It seems like the same root cause for these two issues.
I think we use trains-server v0.12
Was it solved in v0.12.1 ?

Thanks,
Eyal

**Comment by bmartinn** [comment]
Hi @eyalziv ,
It seems there was still some minor issue there, which is now fixed in the new release of Trains-Server v0.13.0

**Comment by eyalziv** [comment]
Thanks Martin!
