### ISSUE TITLE
subparser issue with remote execution

### ISSUE THREAD

**Issue by elinep** [allegroai/trains#74]
Hello trains team,

I have some issues when using argparse with subparser and running script remotely with trains-agent. [Here](https://github.com/elinep/trains_issue_argparse_subparser) is a small repo to reproduce the problem.

I have a script with global parameters and subparser parameters all set to default integer value 1.
```
from argparse import ArgumentParser
from trains import Task

def build_parser():
    parser = ArgumentParser()
    parser.add_argument("--global_param0", type=int, default=1)
    parser.add_argument("--global_param1", default=int(1))

    sub_program_subparser = parser.add_subparsers(dest="sub_program")
    program_subparser = sub_program_subparser.add_parser("program")
    program_subparser.add_argument('--specific_param0', type=int, default=1)
    program_subparser.add_argument('--specific_param1', default=int(1))
    return parser

if __name__ == '__main__':
    # create task
    task = Task.init(project_name='argparser_issue', task_name='test')
    # set manualy requirements, auto detection will timeout
    task._update_requirements("trains")

    parser = build_parser()
    args = parser.parse_args()
    print("parsed arguments:")
    print(args)
```

I can run this script locally and override all my default parameters like this.
```
python script.py --global_param0 2 --global_param1 2 program --specific_param0 2 --specific_param1 2
```
which behaves as expected and outputs
```
parsed arguments:
Namespace(global_param0=2, global_param1='2', specific_param0=2, specific_param1='2', sub_program='program')
```
[remote experiment link on demo server](https://demoapp.trains.allegro.ai/projects/5536614fa22443e1a01113cc38eedf81/experiments/7270c5a3905e4186acc08f9b499749ca/execution)

Now I clone the task on the web interface and run it in a remote fashion. 
```
trains-agent execute --id ID_OF_THE_CLONE_TASK
```
which doesn't behave like the local run. Some arguments are missing and types are not consistent.
```
parsed arguments:
Namespace(global_param0=2, global_param1=2.0, specific_param1=2.0, sub_program='program')
```
[remote experiment link on demo server](https://demoapp.trains.allegro.ai/projects/5536614fa22443e1a01113cc38eedf81/experiments/83b78b91bdfc4623b6e789e8d19ecca7/info-output/log)

Next table summarizes the result and the expected behavior

| params          | expected  | local run | remote run |
|-----------------|:---------:|:---------:|:----------:|
| global_param0   |     2     |     2     |      2     |
| global_param1   |    '2'    |    '2'    |     2.0    |
| sub_program     | 'program' | 'program' |  'program' |
| specific_param0 |     2     |     2     |            |
| specific_param1 |    '2'    |    '2'    |     2.0    |
 
There are 2 issues:
- (minor) when the type is not set the remote run doesn't behave like argparse ('global_param1' and 'specific_param1').
- for remote execution, sub parser arguments are not set when the type is specified as an int.

**Comment by bmartinn** [comment]
Thank you @elinep for the detailed bug report!
These make our life so much easier

In return, here's a fix :)
`$ pip install trains==0.13.0rc2`

A quick explanation on remote-run argparser, remember that you can clone the experiment, edit the arguments values, and execute remotely, with the new set of values.

*Trains* will try to cast variables as precisely as possible when executing in remote execution. This means if type was specified in argparser, *trains* will make sure you end up with the correct type. 
If type was not specified *trains* will use the default value as hint for the type casting. This means that if the default was int (again argparser type was not specified) and the value passed is '1.0', you will end up with int(1), but if the value passed is '1.2' you will end up with float(1.2)

Makes sense?

**Comment by elinep** [comment]
Wouh, that is responsive. I confirm it works. Thanks !

By the way I notice this version is not pushed on your github repository. 
Do you push only when you release ?

Keep up the good work :+1:

**Comment by bmartinn** [comment]
With pleasure :smile: 

p.s.
Yes, only stable releases are pushed to GitHub (RC's are in PyPI only). It gives us more flexibility in releasing bug fixes and testing new features, I guess that's why they call them release-candidates ;)

**Comment by bmartinn** [comment]
Hi @elinep ,
Just letting you know trains v0.13.0 was released, including the same fix :)
`$ pip install trains==0.13.0`
