### ISSUE TITLE
Logarithmic view of scalars

### ISSUE THREAD

**Issue by DdHms** [allegroai/trains#75]
It would be really nice to add the possibility to view some scalar results in a y-axis logarithmic scale. This is very useful for a decaying loss with a very large range of y-axis values.

Thanks,
DD

**Comment by bmartinn** [comment]
Thanks @DdHms , this is a good idea!

I assume it applies mostly to "Scalars", so I imagine adding it as a global setting *"[x] Log Scale"*, like the Wall-Time/Iterations or Smoothing.

What do you think?

**Comment by DdHms** [comment]
Thanks for the quick response.
It would be plausible though it would be best to be a clickable for each
chart apart after all you wouldn't want GPU usage or accuracy graphs to be
logarithmic.

Thanks,
DD

**Comment by bmartinn** [comment]
Makes sense :)

Guys, :+1: to vote , it will bump this feature priority

**Comment by RadaKk** [comment]
I saw in the release of v0.14.0 that this feature has been added.
Could you explain where is the associated button log/non log scale in the UI ? 

thanks

**Comment by bmartinn** [comment]
Hi @RadaKk,

Apologies, it seems we had a build issue - we've just released Trains Server v0.14.1 to fix this issue.
You can see the logarithmic scale in the scalars result page, it is the right-most icon in the icons hover menu that appears when you place the mouse pointer over any scalars plot (you can check it out in our demo server as well).

**Comment by DdHms** [comment]
Just checked out the new feature 👍 
Thanks a lot
