### ISSUE TITLE
Training freezes randomly when using Trains

### ISSUE THREAD

**Issue by yoavhalevi** [allegroai/trains#76]
Hey,

We are trying Trains for almost a week now and ever since we started we encountered random freezing of our training. random in the sense that training freezes in different epoch\step each time.
It happens with different training scripts, that previous to Trains ran with no issue. here are the only lines added to the training script to log Trains task:
`from trains import Task
task = Task.init(project_name="Classifier", task_name="resnet50_GCIv4_NYBv7_NYOv4_WLDv2_INv1")
`

For example with the latest freeze we encountered:
Process keeps running, iterations count in trains experiment still increment:
![image](https://user-images.githubusercontent.com/59438344/71777926-bfb03580-2faf-11ea-91cd-1dbb810a369b.png)
But you can see in the following screenshot that the last training step is 5240/16203 in epoch 19/300 that is frozen from yesterday (4/1/20) with no more logs afterwards:
![image](https://user-images.githubusercontent.com/59438344/71777905-8e376a00-2faf-11ea-8d0c-debef26fef04.png)

we run trains and the training script in a docker image on a GCP vm.

Is it something you encountered before? any ideas what might cause this?

**Comment by bmartinn** [comment]
Hi @yoavhalevi , 

1) What is the python version you are using?
What's the *trains* and *trains-server* versions you are using?
Also, are you manually launching your experiment or is it *trains-agent* ?

2) It seems that the main training thread is stuck (no additional stdout logs), but the process itself is still alive, hence the "last updated a few seconds ago". I'm also assuming the machine monitoring graph keeps updating (see Results, Scalars, ":monitor::machine:")
Do you see anything out of the ordinary in the resource monitoring (e.g. memory consumption, cpu utilization etc...)?

**Comment by yoavhalevi** [comment]
Hey @bmartinn 

Thank you for the quick reply.
here are the answers to your questions:
1. Python 3.5.2, trains 0.12.2.  trains-server v0.12,
currently running the experiment manually without trains-agent.
2. resources drop - no cpu\gpu utilization, memory consumption in gpu stays the same. i see this in the ssh connection to the docker image running the training, in the trains UI I get an error fetching Scalars\Plots.

Since another run without trains froze as well, we take it to further investigation on our end cause it might not be related to trains after all. closing this issue at the moment.
