### ISSUE TITLE
Trains failure to update metrics for certain tasks

### ISSUE THREAD

**Issue by Cptmaxon** [allegroai/trains#82]
Hello getting the following in our logs : 

020-01-02 01:42:47,264 - trains.Metrics - ERROR - Action failed <500/100: events.add_batch/v1.0 (General data error (TransportError(400, 'action_request_validation_exception', 'Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 537;2: id is too long, must be no longer than 512 bytes but was: 537;3: id is too long, must be no longer than 512 bytes but was: 528;')))>
2020-01-02 01:42:47,265 - trains.Metrics - ERROR - Failed reporting metrics: <500/100: events.add_batch/v1.0 (General data error (TransportError(400, 'action_request_validation_exception', 'Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 537;2: id is too long, must be no longer than 512 bytes but was: 537;3: id is too long, must be no longer than 512 bytes but was: 528;')))>

saw this issue in ES:
https://github.com/Norconex/committer-elasticsearch/issues/25

on our end we aren't doing anything special just using dice distance as our metric for best model . and having descriptive task names

**Comment by bmartinn** [comment]
Hi @Cptmaxon ,

Yes you are correct, it is somehow connected to ES limit, that said this bug was fixed in *trains-server* v0.13
Which *trains-server* version are you running?

**Comment by Cptmaxon** [comment]
> Hi @Cptmaxon ,
> 
> Yes you are correct, it is somehow connected to ES limit, that said this bug was fixed in _trains-server_ v0.13
> Which _trains-server_ version are you running?

it is an issue from last week before 0.13, we since upgraded, if you say it's fixed ,I'll close this issue and reopen if I see it's unfixed. 
thanks!
