### ISSUE TITLE
where do reported images/artifacts uploaded to?

### ISSUE THREAD

**Issue by boazpe** [allegroai/trains#85]
Hi,
I use logger.report_image to upload debug images, and those are shown on the experiment page as expected. 
However, when i try to find them in the S3 experiment directory  i don't see them (i only see the 'models' directory).

when i right-click the image and open it in a new browser tab the url is:
MY_TRAINS_SERVER_DNS:8081/PROJECT_NAME/EXPERIMENT_NAME/metrics/FILE_NAME

I tried to use task.setup_upload after task.init but than the experiment directory was not written at all to s3 (but i can still download the model from the trains web-app, which is again quite strange).

I also tried using task.upload_artifact. using this i can see the image under the experiment artifacts, but again, i can't see them on s3.

Any clues to where they are stored?

Thanks,
Boaz

**Comment by bmartinn** [comment]
Hi @boazpe ,

The default `trains.conf` configuration will store all models/artifacts/debug-images on the `trains-fileserver`. Specifically if you are running the *trains-server* with the default configuration, you can find all of them on the *trains-server* machine, under `/opt/trains/data/fileserver`

You can however change the default models/artifacts, to be automatically copied and stored somewhere else by setting the `output_uri` argument when initializing the experiment.

In the following example, all model files and artifacts will be copied to sub-folders in /tmp/data

```python
task = Task.init('examples', 'upload test', output_uri='/tmp/data')
```

And here we will upload a copy of the models / artifacts to an s3 bucket:
```python
task = Task.init('examples', 'upload test', output_uri='s3://bucket/stuff/')
```

If you wish to change the debug-images storage location:

```python
from trains import Logger
Logger.current_logger().set_default_upload_destination('s3://mybucket/logs/')
```

**Comment by boazpe** [comment]
worked perfectly, thanks!

BTW, if i use s3 to store the images, are they being deleted from the server? can i set it so they will be deleted from the server, and the download links on the web-app will fetch them from s3?

**Comment by bmartinn** [comment]
There is a script here: #84 
One could execute it on an s3 mounted bucket using https://github.com/s3fs-fuse/s3fs-fuse
What do you think?

**Comment by boazpe** [comment]
Not sure exactly how it will help me here, but i can live with files being added to the server instance itself for now (currently it has plenty of disk).

Thanks again anyway

**Comment by pedropalb** [comment]
Hi,

I don't think I understand how this works. My trains.conf file is the default one `default_output_uri: ""` and I don't specify an `output_uri` as a Task parameter. I'm running the client in a  docker container on a remote machine. The model location seems to be in a container directory so that when I try to download it to my local host through the web API I get the following error:
`Not allowed to load local resource: file:///models/my-model`

This way I have to go to my remote container, copy the model to a mapped volume in the remote machine and then scp to my local machine.

I thought that a copy would be automatically available through the file server over the <sotarge_ip>:8081. Am I missing something? How can I set it up to download my model from the trains-server through the web API?

Thanks!

**Comment by bmartinn** [comment]
Hi @pedropalb 

Let me try and shed some light on `output_uri`

- When `output_uri` is empty, there is not auto-magic copy of the local model files. They are registered with the local path. in your example `/models/my-model` ('file://' prefix notes it is a local copy)
- When `output_uri` is set to a storage URI, every model file that is stored on the local system, will be automagically copied into the storage URI, with a specific folder for the experiment. For example: if `output_uri` is equal to "http://localhost:8081/" a local `model_file.bin` file will be copied/uploaded to "http://localhost:8081/project_name/experiment_name/models/model_file.bin" (this is not exactly the path that will be created, but it is close enough for this example)

How can we set the output_uri:
1. In code: 
`task = Task.init('example', 'train', output_uri='http://localhost:8081/')`
2. Setting the default value of `output_uri` in `~/trains.conf` : 
`sdk.development.default_output_uri = "http://localhost:8081/"`
3. In the UI, after cloning a Task, you can edit the "Destination":"Output" field, anything there will be used as `output_uri` when the Task is executed by the *trains-agent*

**Comment by pedropalb** [comment]
Thank you for the clarification, @bmartinn!

I am facing an issue on the model upload. I use the tensorflow format which saves the model as a directory and the trains seems to have problems to upload directories:
2020-07-03 01:25:28,710 - trains.storage - ERROR - Exception encountered while uploading [Errno 21] Is a directory: '/models/checkpoints/my_task/10-0.60'

Is there a workaround other than saving the model as hdf5?

Thanks!

**Comment by bmartinn** [comment]
Apologies @pedropalb, I seem to miss this one, probably because it was closed :(
>I am facing an issue on the model upload. I use the tensorflow format which saves the model as a directory and the trains seems to have problems to upload directories:

Actually Trains will automatically zip and upload the entire directory as a signle zip file (and will do the opposite when getting it back).
How can I reproduce this issue ?
What's the Trains / Python / TF versions, and OS type?
