### ISSUE TITLE
How to use my own virtual environment.

### ISSUE THREAD

**Issue by columbo123** [allegroai/trains#87]
How can I use my own virtual environment instead of creating new virtual environment everytime I run the script. Some of the packages don't get installed by pip.
Regards

**Comment by bmartinn** [comment]
Hi @columbo123 ,

Just to clarify, is this issue related to #86 ?

**Comment by columbo123** [comment]
I am not sure but I don't think it is related to the issue #86. I have changed the system site package option to true in the config file which solves my issue, but still trains agent creates new environment every time which takes 30 sec to one minute or more every time I run a new script. Is there any solution to this.
Regards

**Comment by bmartinn** [comment]
*trains-agent* will always create a new virtual environment for any experiment it runs, in order not to mess with the system/its environment.

Notice that the second time it creates the virtual environment, it should only take a few seconds as the python packages are cached locally, and zipping them should not take long ...

I guess waiting a few seconds is better than destroying your own python environment :)

**Comment by columbo123** [comment]
Yes, I also switched on the system site package option, so now I dont think I need to worry about the packages that dont get installed using pip.
