### ISSUE TITLE
Tensorboard saves result for only 5 iterations.

### ISSUE THREAD

**Issue by columbo123** [allegroai/trains#88]
In debug image section images are only saved for 5 iterations. The solution for it is changing the max_image_history from 5 to -1 or any number of iterations I want. The default value of that max_image_history is saved in some global configuration file as written in trains/reporter.py file. But I am not sure which file is global configuration file. If it is trains.conf, then what is the name of the flag.
Thanks in advance

**Comment by bmartinn** [comment]
Hi @columbo123 ,

The config file is indeed `trains.conf`. The flag path is `sdk.metrics.file_history_size` (default value currently set to 100)

**Comment by columbo123** [comment]
But the number of iterations it is showing in tensorboard is only 5, what should I do to increase it?

**Comment by bmartinn** [comment]
Yes, unfortunately it's a UI limit, the next version will allow you to iterate back on all the debug images.
Hopefully should not take long to release :)

**Comment by columbo123** [comment]
Thanks a lot, hoping for a quick release.
