### ISSUE TITLE
error while trying to use my own environment for trains_agent

### ISSUE THREAD

**Issue by tomeramit** [allegroai/trains#91]
Hi,
I configured trains recently and I'm facing the next error while trying to work with my own environment (without installing it):

Current configuration (trains_agent v0.13.0, location: /tmp/.trains_agent.mupmszr8.cfg):

sdk.storage.cache.default_base_dir = ~/.trains/cache
sdk.storage.cache.size.min_free_bytes = 10GB
sdk.storage.direct_access.0.url = file://*
sdk.metrics.file_history_size = 100
sdk.metrics.matplotlib_untitled_history_size = 100
sdk.metrics.images.format = JPEG
sdk.metrics.images.quality = 87
sdk.metrics.images.subsampling = 0
sdk.network.metrics.file_upload_threads = 4
sdk.network.metrics.file_upload_starvation_warning_sec = 120
sdk.network.iteration.max_retries_on_server_error = 5
sdk.network.iteration.retry_backoff_factor_sec = 10
sdk.aws.s3.key =
sdk.aws.s3.region =
sdk.aws.boto3.pool_connections = 512
sdk.aws.boto3.max_multipart_concurrency = 16
sdk.log.null_log_propagate = false
sdk.log.task_log_buffer_capacity = 66
sdk.log.disable_urllib3_info = true
sdk.development.task_reuse_time_window_in_hours = 72.0
sdk.development.vcs_repo_detect_async = true
sdk.development.store_uncommitted_code_diff_on_train = true
sdk.development.support_stopping = true
sdk.development.worker.report_period_sec = 2
sdk.development.worker.ping_period_sec = 30
sdk.development.worker.log_stdout = true
agent.worker_id = trains-agent-lv-beast-keras-dl:gpu0
agent.worker_name = trains-agent-lv-beast-keras-dl
agent.python_binary =
agent.package_manager.type = pip
agent.package_manager.system_site_packages = true
agent.package_manager.force_upgrade = false
agent.package_manager.conda_channels.0 = defaults
agent.package_manager.conda_channels.1 = conda-forge
agent.package_manager.conda_channels.2 = pytorch
agent.venvs_dir = /home/lv-beast/.trains/venvs-builds
agent.vcs_cache.enabled = true
agent.vcs_cache.path = /home/lv-beast/.trains/vcs-cache
agent.venv_update.enabled = false
agent.pip_download_cache.enabled = true
agent.pip_download_cache.path = /home/lv-beast/.trains/pip-download-cache
agent.translate_ssh = true
agent.reload_config = false
agent.docker_pip_cache = /home/lv-beast/.trains/pip-cache
agent.docker_apt_cache = /home/lv-beast/.trains/apt-cache
agent.default_docker.image = nvidia/cuda
agent.default_python = 3.5
agent.cuda_version = 102
agent.cudnn_version = 0
api.version = 1.5
api.verify_certificate = true
api.default_version = 1.5
api.http.max_req_size = 15728640
api.http.retries.total = 240
api.http.retries.connect = 240
api.http.retries.read = 240
api.http.retries.redirect = 240
api.http.retries.status = 240
api.http.retries.backoff_factor = 1.0
api.http.retries.backoff_max = 120.0
api.http.wait_on_maintenance_forever = true
api.http.pool_maxsize = 512
api.http.pool_connections = 512
api.api_server = http://localhost:8008
api.web_server = http://localhost:8080
api.files_server = http://localhost:8081
api.host = http://localhost:8008
Executing task id [49ac8038d0714e32a65b46ad56c88e48]:
entry_point = unpaired_real.py
version_num = 49ca098a868fbf139ed4ba0dadb42b8468700173
tag =
/home/lv-beast/.trains/venvs-builds/3.5/bin/python3.5: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
Using base prefix '/home/lv-beast/miniconda3/envs/keras-dl'
New python executable in /home/lv-beast/.trains/venvs-builds/3.5/bin/python3.5
Also creating executable in /home/lv-beast/.trains/venvs-builds/3.5/bin/python
ERROR: The executable /home/lv-beast/.trains/venvs-builds/3.5/bin/python3.5 is not functioning
ERROR: It thinks sys.prefix is '/home/lv-beast' (should be '/home/lv-beast/.trains/venvs-builds/3.5')
ERROR: virtualenv is not compatible with this system or executable
trains_agent: ERROR: Command '['python3.5', '-m', 'virtualenv', '/home/lv-beast/.trains/venvs-builds/3.5', '--system-site-packages']' returned non-zero exit status 100

It may relate to mistakes in the installation or the execution process as well

Thanks!

**Comment by bmartinn** [comment]
Hi @tomeramit ,
Yes, I think your observation is correct, it seems *trains-agent* cannot create a new virtual environment for the experiment. It fails executing python...

I suggest to reinstall *trains-agent* (no need to worry about the configuration file `~/trains.conf`, it will stay intact)

If *trains-agent* was installed in a virtual environment, I would suggest to remove the broken virtual environment, create a new one and install *trains-agent* in it.

**Comment by tomeramit** [comment]
Should I install trains-agent in a clean environment, or install it inside the local code environment that my training script needs?

**Comment by bmartinn** [comment]
New clean environment, it has nothing to do with your code.
It acts as a true agent, connecting to the *trains-server* pulling experiments and recreating the experiments' environment, and execute them.

**Comment by tomeramit** [comment]
When I install the trains-agent in python 3.7 this does not happen
but when I install it in 3.5.4 (the same python version that my code is) this happens
The python version of the trains-agent can be different from the version of the code? (in case I use my own libraries - python 3.5.4)

**Comment by bmartinn** [comment]
By default, the python version the *trains-agent* uses to launch the experiment, is the same python version it is executed in (notice, it is not the same environment, just the same python version).

You can specify a different python version, by point it to the exact python executable you want *trains-agent* to use.  To do so, set `python_binary` in the configuration file [`~/trains.conf`](https://github.com/allegroai/trains-agent/blob/master/docs/trains.conf#L35).

For example:
```
agent.python_binary = "/usr/local/bin/python3.7"
```

**Comment by tomeramit** [comment]
I installed trains-agent on python 3.7, and:
agent["python_binary"] = "home/miniconda/envs/env/bin/python" my conda environment that I want trains-agent to use and not install (python 3.5.4)

but getting error:
/home/lv-beast/.trains/venvs-builds/3.5/bin/python: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
Using base prefix '/home/lv-beast/miniconda3/envs/keras-dl'
New python executable in /home/lv-beast/.trains/venvs-builds/3.5/bin/python
ERROR: The executable /home/lv-beast/.trains/venvs-builds/3.5/bin/python is not functioning
ERROR: It thinks sys.prefix is '/home/lv-beast' (should be '/home/lv-beast/.trains/venvs-builds/3.5')
ERROR: virtualenv is not compatible with this system or executable
trains_agent: ERROR: Command '['/home/lv-beast/miniconda3/envs/keras-dl/bin/python', '-m', 'virtualenv', '/home/lv-beast/.trains/venvs-builds/3.5', '--system-site-packages']' returned non-zero exit status 100.

tried to reinstall, but didn't help, dont know if it's assuming external python or vitualenv installation (I want to use my conda environment as is, so dont know if it should call virtualenv at all)

**Comment by tomeramit** [comment]
I had to install python 3.5.4 on ubuntu and then to set the LD_LIBRARY_PATH to it and then it solved
