### ISSUE TITLE
Grouping projects into folders and subfolders

### ISSUE THREAD

**Issue by crazyfrogspb** [allegroai/trains#92]
Hey guys,

Here is a suggestion for improving experience of working with trAIns - grouping Projects into folders and subfolders in UI. Right now we have about 30-40 Projects in trAIns, and some of them are related to the same project in our company. The only way to filter them at the moment is by using search which is not ideal. 

Thanks for an amazing project!

**Comment by bmartinn** [comment]
Hi @crazyfrogspb , thanks for the idea!
This is already in development, but here is a quick glimpse into what we are designing

- Projects and sub-projects in the Project page (basically you press on a card and you get a list of sub-projects, with the same UI card design). Currently we are thinking a single sub-project level is enough, but we are open to discussion. Our fear from multiple level sub-projects (i.e. sub-sub-project) is that very quickly you will end up with a tree like structure, and then it's just a different kind of mess...
- Experiment Tags, free text tags per experiment , allowing you to quickly filter different types of experiments in the system, with multiple tags support. This would allow for a different way to organize experiments inside a single project (for example, data pre-processing vs training, and the alike...)

What do you think ?

p.s.
Thank you for the compliments, it is always appreciated :)

**Comment by metya** [comment]
It is great news! I always want some kind of grouping or sorting my experiments in projects. So tags it is a very good idea for organizing. So one level sub-folders and tags it is definitely would be enough in my opinion.
