### ISSUE TITLE
Authentication with git failed

### ISSUE THREAD

**Issue by tomeramit** [allegroai/trains#93]
Hi,
I'm trying to set the credentials for the git, I tried to set the specific user/pass in the fields of agent.git_user, agent.git_pass and inside the area of agent{} the fields git_user,git_pass as well.
this did not work, (receive error for clone from address "https://user_name:pass@repo_address.git/")

when I try in terminal with this "https://user_name:pass@repo_address", (without the ".git/") the clone succeeds

Tried to leave blank for ssh as well, but didn't work as well (although I can do it from terminal as well)

this is my remote url
git config --get remote.origin.url:
https://bodyvisionmedical.visualstudio.com/repo_address

but on repository in the server it appears as 
https://bodyvisionmedical.visualstudio.com/repo_address.git

I found the function that do this:
    def _post_process_info(self, info):
        if info.url and not info.url.endswith(".git"):
            info.url += ".git"

but after I remove this and getting the url without the .git the trains agent still fails, maybe the trains-agent try to clone from git if there is .git in the end?
(repo does not apear to be an hg repository)

Thanks

**Comment by bmartinn** [comment]
Hi @tomeramit ,

It seems your are correct, Microsoft (Azure) decided not to adhere to the ".git" url ending standard ...

Every git repository hosting solution we are aware of, will have its git repository urls end with `.git`, making it obvious that this link point to a repository, rather then other web services.

This assumption was built into *trains*, as a way to differentiate git urls from other VCS repositories.

I'll make sure the next version of *trains* does not add the ".git" to the url, as it seems to break the links to Azure DevOps repositories.

In the meantime, you can "clone" the experiment (right-click select clone) then edit the newly cloned experiment, and change the url link, removing the ".git" suffix.

Then, you need to upgrade *trains-agent* to the latest RC, now supporting git repository url links without .git ending:
`$ pip install trains-agent==0.13.1rc10`

**Comment by tomeramit** [comment]
Thanks!

**Comment by tomeramit** [comment]
There is need to upgrade the trains package as well? (In my code I removed this lines for that to work)

def _post_process_info(self, info):
    if info.url and not info.url.endswith(".git"):
    info.url += ".git"

**Comment by bmartinn** [comment]
Hi @tomeramit ,

You are correct, we've just released trains v0.13.2 which includes this change as well :)

**Comment by tomeramit** [comment]
thanks
