### ISSUE TITLE
setting the PYTHONPATH of the trains-agent

### ISSUE THREAD

**Issue by tomeramit** [allegroai/trains#94]
There is an option to set the python path for the trains-agent from the config file? (or somewhere else?)

**Comment by bmartinn** [comment]
Hi @tomeramit ,

_trains-agent_ will take the PYTHONPATH in its environment and add that to the PYTHONPATH used when running the experiment.

So, while you can't set that in the config file, you can set PYTHONPATH when running the agent, for example:
`$ PYTHONPATH=/my/custom/path trains-agent daemon --queue default`

**Comment by tomeramit** [comment]
thanks!
