### ISSUE TITLE
[Feature request] Auto-clear 

### ISSUE THREAD

**Issue by majdzr** [allegroai/trains#97]
Hey,

As you can imagine, when intensively using trains while developing, many failed experiments stack up in that specific project until _the_ experiment is finally running. Is it possible (maybe you already have it and I totally missed it) to have an automatic (delayed) clearance of these experiments (failed, low/zero number of iterations, no artifacts etc..). 

Thanks and keep this awesome project alive!

**Comment by bmartinn** [comment]
Hi @majdzr ,

Similar to #84, it is possible to create a script that can periodically find all experiments that match your criteria and "clean them up".

I'll be happy to provide such an example, but first, assuming that's what you're after, what would you consider as "cleanup"? Will moving these experiments to the archive be enough? Are you bothered by the "visual clutter" or by other side-effects (such as files in the file server etc.)?

**Comment by majdzr** [comment]
@bmartinn  thanks again for your reply.

I think the visual mess is what bothers me, so archiving these would be super helpful.

The simple scenarios are "less than N iterations" or/and "less than T seconds from T0" or/and "failed status". This behavior should be toggled off in case it bothers the user.

Thanks in advance!

**Comment by bmartinn** [comment]
Hi @majdzr,

Currently, doing this required _trains-agent_ - I'll add an example there soon and send you the link :)

**Comment by majdzr** [comment]
Hey @bmartinn,

Yes sure. I'm already enjoying the trains-agent!
Thanks a lot.

**Comment by bmartinn** [comment]
Hi @majdzr, 

Please see [this](https://github.com/allegroai/trains-agent/blob/master/examples/archive_experiments.py) example script. It basically provides everything you've requested, and you can run it as a cron job if you'd like a regular clean-up of experiments.

The script allows you to provide different criteria from the command line. If you add any more functionality (or find a bug) I'll appreciate a pull-request :)

Also, although this is not a destructive script, **please test it and backup your data** in advance before trying it out... :)

**Comment by majdzr** [comment]
@bmartinn Thanks a lot for this.
