### ISSUE TITLE
Fastai support

### ISSUE THREAD

**Issue by shobhit9618** [allegroai/trains#99]
I was trying to use a fastai code and run model training along with trains. Experiment gets logged on the server, but no graphs are generated (expect GPU usage graphs). Is there a solution for this?

**Comment by bmartinn** [comment]
Hi @shobhit9618, 
Just making sure here, the console is being logged? And the git repository (or single script) are registered under the Execution tab? Alongside the python packages ?

Regrading graphs, are you using TensorBored (LearnerTensorboardWriter) with FastAI  to visualize graphs? Is it manually with Matplotlib ?

**Comment by shobhit9618** [comment]
Hello @bmartinn ,
The console is being logged when running directly. But, when I run via nohup, I cannot see the training bar (this might be because training bar is also not visible in nohup output file). Regarding git repository, it gets registered in the execution tab.
Currently I'm visualising the graphs using matplotlib only (graphs are saved after training is complete). Not using LearnerTensorboardWriter as of now. Also, I'm running a python script. But the same issue occurs when running on Jupyter notebook also.
Should I try using tensorboard? Also, is there a solution for the nohup problem?
(I have used trains with my Keras model and am able to view all graphs and logs perfectly.)

**Comment by shobhit9618** [comment]
Update:
I added LearnerTensorboardWriter callback and now am able to see graphs in trains server.
But, all 3 plots for accuracy, train_loss and valid_loss are getting plotted on the same graph, whereas they are plotted differently when checked in tensorboard.
Can you guide on how to get separate graphs in trains?

**Comment by bmartinn** [comment]
@shobhit9618 it seems your observation regarding the progress bar is correct, `fastai` will not output it when running with nohup. That said, I found a reference to the issue [here](https://forums.fast.ai/t/running-with-console-progress-bar-in-jupyter-notebook/36066/5), it seems you can force the progress bar with `fastai.basic_train.progress_bar = fastprogress.force_console_behavior()`

Regrading the Tensorboard graphs, I think you are describing the old behavior, If I remember correctly after v0.12 we changed the graphs to match the Tensorboard display (one per graph). 

What's your  *trains* version ? I suggest upgrading to the latest version, if the problem consists  please specify the exact expected graphs title/series and the output your are getting.

**Comment by shobhit9618** [comment]
Hi @bmartinn ,
Thank you for your help. 
I will look into the solution you mentioned for the progress bar problem. No issue with that, other logs are visible and I'm fine with it. 

I haven't updated the trains server docker image, but my current trains version is 0.13.2 on both the sever side and the agent side. I was just worried I might lose my trains data if something goes wrong.
I'll be updating it in the near future.

Also, I just checked the matplotlib graphs and yes, I can view them in the plots section.
But their naming is not proper. It is showing the confusion matrix graph name correctly, but for other graphs like accuracy, loss, it's just naming them untitled followed by 'iteration' and iteration number.
Is there a way to explicitly name the graphs?

**Comment by bmartinn** [comment]
Hmm... just using *trains* v0.13.2 should be enough to get the Tensorboard plot-per-graph sorted (regardless of the *trains-server* version). 
What exactly are the graphs you expect to get, and what are you getting?

As for the `matplotlib`, you can set the *trains* plot title by setting the matplotlib graph title :)
You can take a look at the matplotlib example [here](https://github.com/allegroai/trains/blob/master/examples/matplotlib_example.py#L34)

BTW: No reason not to upgrade the *trains-server*, it should have no effect on stored experiments (I mean you should backup the `/opt/trains` folder before the upgrade, but it is just an additional precaution, it is not really needed in the upgrade process)

**Comment by shobhit9618** [comment]
Hey @bmartinn,
Please see a sample graph that I am getting.
![model_graph](https://user-images.githubusercontent.com/19635587/73597870-f057a080-4556-11ea-8564-b0a171f3eeee.png)
I wish to have all 3 parameters in separate graphs (as is visible in tensorboard).

Regarding matplotlib, I added the plot title and it's working as expected. Thanks a lot for this.

Also, I will update the trains server soon.

**Comment by bmartinn** [comment]
Thanks @shobhit9618 for the screen grab.

The current behavior for *trains* is to have the tensorboard scalar name's first token (separated with '/') defining the graph title, then the rest become the series title.
In our example "metrics/accuracy" becomes, graph title "metrics" series name "accuracy".

The idea is that Tensorboard is always in "comparison" mode, where you have multiple experiments, and you want the graph to show a series per experiment. Whereas in *trains* the default view is a per experiment view, where one would want to optimize screen real-estate and group similar plots on the same graph when they have the same context (for example loss, training/validation). Of course that when comparing experiments *trains* will split everything to a plot-per-graph like Tensorboard, as a single graph will show results from multiple experiments.

Specifically you could change the `fastai` scalar logging from `metrics/accuracy` to `performance/accuracy` , then you will end up with two graphs, one "metrics" and one "performance"

Anyhow, I think it is a good idea to add additional level of control, where you could tell *trains* to store scalars as plot-per-graph , matching the Tenorboard behavior.

What do you think?

**Comment by shobhit9618** [comment]
Hey @bmartinn,
Thank you for all your suggestions and help.

I don't quite understand this statement: 'change the `fastai` scalar logging from `metrics/accuracy` to `performance/accuracy`'. How do I change the scalar logging? (When creating `learner` in `fastai`, it has a parameter called metrics, which I'm setting to accuracy). 
Anyways, on clicking on the `accuracy` parameter in trains graph, I can view the accuracy graph separately which is okay for me.

Regarding adding additional level of control, I think it would be a great option to the user. You can keep the default as the current one, and allow the user to set a parameter to store scalars as plot-per-graph.
Another feature request: Can you add a filter on the home page of the server to show only the running experiments? It would be helpful to users running multiple models at once and would only like to check the running ones at a time.

**Comment by bmartinn** [comment]
Hi @shobhit9618 , 
I guess it is not straight forward to change the way *fastai* is reporting loss/accuracy...

I'll update here once we have an RC with the suggested Tensorbaord behavior

BTW, what do you mean by? 
>  It would be helpful to users running multiple models at once and would only like to check the running ones at a time.

In the home screen there is a section "Recent Experiments", showing the currently running or recently completed experiments.

**Comment by shobhit9618** [comment]
Hi @bmartinn ,
Thank you for taking this issue into consideration.

Regarding experiments, currents the trains UI only shows 4-5 latest experiments at a time. In some cases, if someone runs an experiment and has to abort it immediately, it still get logged into the recent experiments. There are cases when someone is running maybe 10-15 experiments at a time. In such cases, it's sometimes difficult to find only the ones which are currently running and not just the latest ones (there may be some experiments which might be running even if the newer ones have completed).

So, I think it might be useful for users to have an option to just view the experiments which are currently running. Just adding a small filter on the home screen would work. I hope you understand this concern.

Also, this is a really useful open source tool for ML. Great job maintaining it and listening to user issues.

**Comment by bmartinn** [comment]
Hi @shobhit9618, is this what you had in mind ?
https://allegro.ai/docs/tutorials/tutorial_building_leader_board
See "Section 2" you can filter based on task status 

BTW: yes we finally have documentation :)

**Comment by bmartinn** [comment]
Hi @shobhit9618 
I wanted to update that with the 0.16 release of `trains`, there is now official support for `fastai`. 
You can check this [example](https://github.com/allegroai/trains/blob/master/examples/frameworks/fastai/fastai_with_tensorboard.py) for details.

**Comment by shobhit9618** [comment]
Hi @bmartinn ,
Thank you for the update, it will be helpful for me in the future.
